### ISSUE TITLE
envelope-function and pre-simulated patterns: Number of patterns not recognized

### ISSUE THREAD

**Issue by antiphon** [spatstat/spatstat#10]
The envelope-function assumes that the user gives pattern-lists of length 99.

```
library(spatstat)
x <- rpoispp(100)
f <- ppm(x, i = Strauss(0.001))
sims <- simulate(f, nsim = 5)

envelope(x, pcf, simulate = sims)
#Error in envelopeEngine(X = X, fun = fun, simul = simrecipe, nsim = nsim,  : 
#  Number of simulations (99) exceeds number of point pattern datasets supplied

envelope(x, pcf, simulate = sims, nsim = length(sims))
# no error
```

R 3.2.1
spatstat 1.42.2.2

**Comment by baddstats** [comment]
Thanks - The number of simulations is specified by nsim, which defaults to 99, so this is not strictly a bug. However I guess what you're saying is that most users would expect 'envelope' to set  nsim = length(simulate) when 'simulate' is a list of point patterns and nsim is not given. I guess we can do that. Thanks for pointing it out. A

**Comment by baddstats** [comment]
On second thoughts, this might be complicated. Sometimes a second set of simulations is required (eg global=TRUE and X is a point process). Then we want nsim + nsim2 = length(simulate). I'm not sure how to guess the user's intention easily. A

**Comment by antiphon** [comment]
In my usecase I want to compute envelopes from the pre-defined set of simulations. This always(?) excludes global =TRUE as 
1.  when X is 'ppm' the average can't be guaranteed to be correct for 'simulate' 
2. when X is 'ppp' there is no model specified for deriving the average

**Comment by baddstats** [comment]
The following is possible, where the 'simulate' argument has to have 2 * nsim entries:
    a <- rStrauss(100, 0.5, 0.05, nsim=38)
    E <- envelope(cells, Gest, simulate=a, nsim=19, global=TRUE)

**Comment by antiphon** [comment]
imho it would be better behaviour if the `nsim` and `nsim2` would adapt to `length(a)` . It would solve the original issue, and would not waste patterns as in e.g.
```
a <- rStrauss(100, 0.5, 0.05, nsim=38)
E <- envelope(cells, Gest, simulate=a, nsim=15, global=TRUE)
```
which assumes `nsim2=nsim` and leaves over the `38-15*2=8` patterns. Another reasonable scenario is the case "here's a bunch of patterns, compute the global average from 10 of them", i.e. 
```
E <- envelope(cells, Gest, simulate=a, nsim2=10, global=TRUE)
```
which crashes as `nsim=99` is fixed and `nsim+nsim2 > length(a)`.
