### ISSUE TITLE
Using mppm() with different windows for "clipwin"

### ISSUE THREAD

**Issue by StefanBRas** [spatstat/spatstat#100]
Hi.

I'm trying to fit some models with `mppm`, but with a different window passed to each model by the `clipwin` argument.

Is it correct that this is not possible as the code is right now? It seems like I am only able to pass a single window, that acts as the clipwin argument for each model.

I made some (crude) alterations which made it possible but I was unsure if there was/is reasons for having it this way.

Below is a example of what I am trying to do and even more below is the alterations I made which made it possible

```
library("spatstat")
pp1 <- ppp(x <- runif(20),
         y <- runif(20))

pp2 <- ppp(x <- runif(20),
          y <- runif(20))

tempfunction <- function(x, y) runif(1) * (sin(y) + cos(x))
covariateim1 <- as.im(tempfunction, unit.square())
covariateim2 <- as.im(tempfunction, unit.square())

window1 <- owin(c(0,0.5),c(0, 0.5))
window2 <- owin(c(0.5,1),c(0.5,1))

# fit one for each
ppm(pp ~ covariateim1, clipwin = window1)
ppm(pp ~ covariateim2, clipwin = window2)

# try to do it with mppm
hyper <- hyperframe(pps = list(pp1, pp2),
                    covariateims = list(covariateim1, covariateim2),
                    owins = list(window1, window2))

mppm(pps ~ covariateims, data = hyper) # works, but fits to entire unit square
mppm(pps ~ covariateims, data = hyper, clipwin = owins) # does not work
mppm(pps ~ covariateims, data = hyper, clipwin = list(window1, window2)) # does not work
```
The problem happens in line 34-36 in `mpl.engine'.

It can be fixed by modifying line 168-183 in the file `mppm.R' as this: 

 ```
<line 167> 
clipwins <- list(...)$clipwin # Insert this line
for (i in 1:npat) {
  Yi <- Y[[i]]
  covariates <- if (has.covar) 
    covariates.hf[i, , drop = TRUE, strip = FALSE]
  else NULL
  if (has.design) {
    covariates[dfvarnames] <- lapply(as.list(as.data.frame(covariates[dfvarnames])), 
                                     as.im, W = Yi$data$window)
  }
  tempDots <- list(...) # <---------------------- insert this one
  tempDots[["clipwin"]] <- clipwins[[i]] # <- insert this one
  prep0 <- do.call(bt.frame, list(Q = Yi, trend = trend, 
                                  interaction = Poisson(), ... = tempDots, covariates = covariates, 
                                  allcovar = TRUE, use.gam = use.gam)) # modify this one
< line 183 > 
```

Package/system information:
```
Package: spatstat
Version 1.59-0
Date: 2019-03-22
Built: R 3.6.0; x86_64-pc-linux-gnu; 2019-05-01 09:33:00 UTC; unix
```
  
I wouldn't mind making a pull request but if this was to be changed, one could obviously do it in a better way than this.

Kind regards,
Stefan

**Comment by baddstats** [comment]
Thanks for the suggestion. This would require changes to the code that supports the `”mppm”` class. We will give it some further thought. 

The argument `clipwin` to `ppm.ppp` is designed mainly for internal use by other code. Users can get the same effect as `clipwin` by subsetting the point pattern dataset using `[`.
