### ISSUE TITLE
area.owin bug

### ISSUE THREAD

**Issue by coreydevinanderson** [spatstat/spatstat#106]
Something is amiss with area.owin() in the new version of spatstat. I noticed the problem when trying to get the area of polygon (that was converted from a shapefile)...but it seems to be more general.

my.win <- square(10)
area(my.win)

#Throws the following error
Error in area(my.win) : argument "b" is missing, with no default

#Not sure what argument "b" is...and I don't see this exemption in the source code

**Comment by rubak** [comment]
My best guess is that you are actually calling `area` from another package. Did you load other packages than `spatstat`? Do you get the same error with `spatstat::area(square(10))`?

**Comment by coreydevinanderson** [comment]
You are correct. 'MASS' was also open and this caused the error....and would explain the mysterious argument "b".


Sorry for the confusion. I should have remembered to close all other packages and open 'spatstat' in isolation.

________________________________

**Comment by rubak** [comment]
That's OK. I have done this mistake plenty of times myself. It's a good reminder for us all to make a simple reproducible example of any bug and run it in a vanilla R session to double check things.
