### ISSUE TITLE
Error in `Gfox` with `owin` objects

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#109]
Bug identified in [this question on SO](https://stackoverflow.com/q/57421556/3341769).

Bugfix attempted in Gfox branch, but I'm unsure whether this is the best way to solve the problem. This should be looked into in a bit more detail.

Simple reprex generating the error:

```
library(spatstat)
Y <- as.polygonal(heather$coarse)
X <- runifpoint(100, win = complement.owin(Y))
Gfox(X, Y)
```

**Comment by baddstats** [comment]
Fixed  in `spatstat 1.60-1.023`
 (with a more extensive rewrite, and a new argument `W`)
