### ISSUE TITLE
Multitype interactions with mppm

### ISSUE THREAD

**Issue by jacobbedia** [spatstat/spatstat#111]
Hello,
I am trying to fit a Multitype Strauss Hardcore model to a hyper frame containing four marked point patterns, each with the same 7 marks. I want to use the same interaction/hardcore parameters for all point patterns. When I go to fit the model via mppm, I get the following error:
<img width="1003" alt="Screen Shot 2019-08-14 at 11 13 58 PM" src="https://user-images.githubusercontent.com/45866128/63076182-348faf80-bee9-11e9-8a82-02fd5d75c433.png">

Here is the sample code that I am trying to run. ```ppp_hyperframe``` contains one column with the point patterns (```ppp_data```) and one column of each point pattern's group (```File_Num```). Thank you!

```
num_marks <- 7
iradii <- 10*ones(num_marks)
hradii <- 5*ones(num_marks)
Int <- MultiStraussHard(iradii=iradii, hradii=hradii)
multmodel <- mppm(ppp_data ~ File_Num*polynom(x,y,3), data=ppp_hyperframe, interaction=Int)
```

**Comment by rubak** [comment]
We do not use GitHub Issues for questions and answers. Only genuine bugs. Please make a reproducible example and post it as a question under the `spatstat` tag on StackOverflow.com (preferable) or email it directly to us. If you cannot make a reproducible example without sharing confidential data try to give as many details as possible including which packages you are using. If I try to run your code it already fails on the second line:

    Error in ones(num_marks) : could not find function "ones"

Also, test whether you can fit a single model to a single data set using `ppm(X ~ polynom(x,y,3), interaction = Int)`, where `X` is one of your point patterns. If that already fails you have a simpler problem to debug.

**Comment by baddstats** [comment]
There does appear to be a bug here:

    library(spatstat)
    H <- hyperframe(X=solist(amacrine, amacrine))
    Int <- MultiStraussHard(iradii=matrix(0.1, 2, 2), 
                                             hradii=matrix(0.02,2,2), 
                                             types=levels(marks(amacrine)))
    mppm(X ~ x, data=H, interaction=Int)


This yields the same error.
I will investigate.

**Comment by baddstats** [comment]
Sorry, my mistake, that code does not generate the error.

**Comment by baddstats** [comment]
@jacobbedia, please check that each of the point patterns in your hyperframe had the same vector of possible types. You can do that by 

     typelist <- lapply(lapply(ppp_hyperframe$ppp_data, marks), levels)
     length(unique(typelist)) == 1

which should return `TRUE`. If it returns `FALSE`, then print `typelist` to see what is specified for the possible types of each of the point pattern datasets.
