### ISSUE TITLE
Bug in studpermu.test

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#113]
[Bug report on StackOverflow](https://stackoverflow.com/q/58313274/3341769):

I am using studpermu.test on a large hyperframe of ppp objects and it returns an error.

I am using studpermu.test on a large hyperframe of 250 ppp objects, each with thousands of points (~ 2000-5000), and a grouping factor with 5 levels, with equal group sizes of 50. The function runs successfully on a smaller subset of point patterns but returns an error when I try to run the function on the on the whole hyperframe.

```
> head(runlisthyp)
Hyperframe:
  pointpats parameter
1     (ppp)        30
2     (ppp)        30
3     (ppp)        30
4     (ppp)        30
5     (ppp)        30
6     (ppp)        30
> Kestresult <- studpermu.test(runlisthyp, pointpats ~ parameter, rinterval=NULL, rsteps= 128, nperm = np, use.Tbar = FALSE, minpoints= 10, summaryfunction = Kest)

```

```
Error in if (npossible < max(100, nperm)) warning("Don't expect exact results - group sizes are too small") : missing value where TRUE/FALSE needed 
In addition: Warning message: In factorial(sum(m)) : value out of range in 'gammafn'

```
When the function is run with a subset of 100 ppp objects from the hyperframe I get the following results:

```
> Kestresult
Studentized permutation test for grouped point patterns
pointpats ~ parameter
2 groups: 30, 40
summary function: Kest, evaluated on r in [0, 16.25]
test statistic: T, 999 random permutations
data:  runlisthyp T = 961.06, p-value = 0.001 alternative hypothesis: not the same K-function

```

**Comment by rubak** [comment]
This is fixed with a one line change in the new branch `studpermutest.R` which should be merged when convenient:

https://github.com/spatstat/spatstat/compare/studpermutest.R?expand=1

**Comment by baddstats** [comment]
Done. Thanks!
