### ISSUE TITLE
Bug in quantess.owin

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#116]
On rare occasions `quantess.owin` can generate a tessellation where some tiles have identical names leading to miscalculations in e.g. `cut.ppp` (fewer mark labels than tiles) etc.

Problematic code:
https://github.com/spatstat/spatstat/blob/402e325fcd4d7ac3c6df1a414a586a9f9fe54676/R/quantess.R#L44-L46

Reproducible example:
``` r
library(spatstat)
#> Loading required package: spatstat.data
#> Loading required package: nlme
#> Loading required package: rpart
#> 
#> spatstat 1.61-0.021       (nickname: 'New improved formula') 
#> For an introduction to spatstat, type 'beginner'
X <- shift(chorley, vec = c(1e6, 0))
tes <- quantess(X, "x", 4)
tilenames(tes)
#> [1] "[1e+06,1e+06)" "[1e+06,1e+06)" "[1e+06,1e+06)" "[1e+06,1e+06]"
nlevels(marks(cut(X, tes)))
#> [1] 2
```

**Comment by baddstats** [comment]
Dang. Well spotted.

I recall that you (@rubak) fixed a similar problem in another piece of code by looking at how `cut.default` generates the labels. 

I have copied the code from `cut.default` into a new function `spatstat.utils:makeCutLabels` and uploaded it in `spatstat.utils 1.15-0`. 

I will rewrite `quantess.R` to use `makeCutLabels` in all the (3) relevant places.

**Comment by baddstats** [comment]
`spatstat 1.61-0.028` includes @rubak's example code in the test suite, and passes. 
So this appears to be fixed.
