### ISSUE TITLE
rshift.psp does not like marks

### ISSUE THREAD

**Issue by ute** [spatstat/spatstat#118]
m <- data.frame(A=1:10, B=letters[1:10])
X <- psp(runif(10), runif(10), runif(10), runif(10), window=owin(), marks=m)
Y <- rshift(X, radius = 0.1)

**Comment by ute** [comment]
My quickfix (pull request) does not help if the marks are data frames with one variable. That is because append.psp coerces these marks into a vector. Is that on purpose? Would it break some functionality if append.psp keeps the mark structure? The culprit is %mapp%.

**Comment by baddstats** [comment]
The code for marks of point patterns (`ppp`) coerces a 1-column data frame to a vector. 
The code for marks of `psp` is less well-developed but what should happen in your example is that `marks(X)` should be a vector, i.e. the data frame would be coerced. So that is a bug in `psp`.

**Comment by baddstats** [comment]
On second thoughts we will allow a single-column data frame of marks, and see if that breaks anything else.

**Comment by baddstats** [comment]
It's fixed in `spatstat 1.61-0.053`
