### ISSUE TITLE
Plotting lineardisc fails in Rmd (and probably Rnw)

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#121]
A Rmd with the following chunk will not render:
```{r}
library(spatstat)
d <- lineardisc(simplenet, x = c(.5,.5), .1)
```
It works in an interactive session. It also works if `plot(simplenet)` is called first.

The problem is that the check for whether to initiate a new plot is not robust enough:
https://github.com/spatstat/spatstat/blob/6492f0f22ddc6dc1721902019b4ca9fc081876af/R/lineardisc.R#L136-L139

Inside a Rmd the value of `dev.cur()` is something like `c(png = 2)`, so it doesn't initiate a new plot. I guess a simple solution is to have another argument `add = TRUE`, which decides whether or not to start a new plot when `plotit = TRUE`. If `add=TRUE` one should in my humble opinion get an error if there is no current plotting device active just like for `plot.ppp` etc. This behaviour would not be backwards compatible...

**Comment by baddstats** [comment]
Fixed as you suggested, in `spatstat 1.62-2.006`
