### ISSUE TITLE
Saving intermediate states in rmh

### ISSUE THREAD

**Issue by jbeds** [spatstat/spatstat#124]
I'm using spatstat_1.63-0.004, and I'm attempting to simulate a point process and save the intermediate states every 1e4 iterations. The docs say there should be a saved attribute for the return value of rmh, but the following code block doesn't show one. Thanks for the help!

```
library(spatstat)
num_marks <- length(unique(marks(amacrine)))
iradii <- .1*matrix(1,nrow=num_marks,ncol=num_marks)
MSH1 <- MultiStraussHard(iradii=iradii)
x <- ppm(amacrine, trend =~polynom(x,y,3), interaction=MSH1)
control <- rmhcontrol(nrep=5e5, nsave=1e5)
y <- rmh(x,control=control)
y$saved
```

**Comment by rubak** [comment]
In R an attribute is not the same as a list element (which you are trying to access with `$`). Rather you should use:

    attr(y, "saved")

That gives me a list of point patterns with your example code.

**Comment by baddstats** [comment]
There was already an example of  `attr(, "saved")` in the help for `rmh.default`, but I will make this clearer.
