### ISSUE TITLE
spatsat will not install in anaconda3 Rstudio under mac catalina

### ISSUE THREAD

**Issue by gkinglisboa** [spatstat/spatstat#125]
I have a new installation of Anaconda (anaconda3).  I launch Rstudio from the anaconda navigator app and try to install spatstat.  But the installation has a problem with polyclip.  Any suggestions?  
Here is the output reporting the error...

* installing *source* package ‘polyclip’ ...
** package ‘polyclip’ successfully unpacked and MD5 sums checked
** using staged installation
compiling under C++11
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/var/folders/jn/h6ylmng10p7bdsy68s81zbfm0000gq/T/Rtmpu5XZw3/R.INSTALL310b7a44fd23/polyclip':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
ERROR: configuration failed for package ‘polyclip’
* removing ‘/Users/gregking/anaconda3/lib/R/library/polyclip’
Warning in install.packages :
  installation of package ‘polyclip’ had non-zero exit status
ERROR: dependency ‘polyclip’ is not available for package ‘spatstat’
* removing ‘/Users/gregking/anaconda3/lib/R/library/spatstat’
Warning in install.packages :
  installation of package ‘spatstat’ had non-zero exit status

**Comment by rubak** [comment]
This seems like [this issue](https://github.com/baddstats/polyclip/issues/15). Could you try to install some other R package to check whether it is a general issue with your setup or if it is related to spatstat/polyclip? E.g. try to run this command in your R terminal:

    install.packages("nloptr", type = "source")

**Comment by gkinglisboa** [comment]
Thanks. I tried your suggestion and again had the same kind of error (below).
Next I close everything and in terminal updated all using conda.
Then went back to navigator, launched RStudio and repeated your example.
Again the same error:

* installing *source* package ‘nloptr’ ...
** package ‘nloptr’ successfully unpacked and MD5 sums checked
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/private/var/folders/jn/h6ylmng10p7bdsy68s81zbfm0000gq/T/RtmpUjINwJ/R.INSTALL9e51245fe770/nloptr':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
ERROR: configuration failed for package ‘nloptr’
* removing ‘/Users/gregking/opt/anaconda3/lib/R/library/nloptr’
Warning in install.packages :
  installation of package ‘nloptr’ had non-zero exit status




On 2 Feb 2020, at 21:02, Ege Rubak <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems like this issue<https://github.com/baddstats/polyclip/issues/15>. Could you try to install some other R package to check whether it is a general issue with your setup or if it is related to spatstat/polyclip? E.g. try to run this command in your R terminal:

install.packages("nloptr", type = "source")

**Comment by rubak** [comment]
OK. This confirms that it is a problem with your setup and not spatstat/polyclip. You can try to see if everything works if you only use binary packages:

    install.packages("polyclip", type = "binary")
    install.packages("spatstat", type = "binary")

**Comment by gkinglisboa** [comment]
Alas, I am unable to try your suggestion.  The message returned was …

Error in install.packages : type 'binary' is not supported on this platform

:-(

greg


On 2 Feb 2020, at 22:10, Ege Rubak <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. This confirms that it is a problem with your setup and not spatstat/polyclip. You can try to see if everything works if you only use binary packages:

install.packages("polyclip", type = "binary")
install.packages("spatstat", type = "binary")

**Comment by rubak** [comment]
OK. I think you need to search for help on installation of R and R packages in the Anaconda community. If you just need to use R and spatstat I would recommend that you simply install the official R.app from https://cran.r-project.org/bin/macosx/ and possibly [RStudio](https://rstudio.com/) as an IDE. This is well tested and usually works without any problems.

I'm going to close this now since there isn't much we can do to help with the situation.

**Comment by gkinglisboa** [comment]
Hello Ege,

I agree.  Thanks.  One more reason to move from macos to linux!

greg


On 3 Feb 2020, at 09:58, Ege Rubak <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. I think you need to search for help on installation of R and R packages in the Anaconda community. If you just need to use R and spatstat I would recommend that you simply install the official R.app from https://cran.r-project.org/bin/macosx/ and possibly RStudio<https://rstudio.com/> as an IDE. This is well tested and usually works without any problems.

I'm going to close this now since there isn't much we can do to help with the situation.

**Comment by gkinglisboa** [comment]
Dear Ege,

An update…

I had homebrew working as my mac package manager.  It retrieved and installed everything that was needed to get R (version 3.6.2) up and running.
I then downloaded RStudio, installed, launched it and loaded spatstat without any problems whatsoever.

The macos Anaconda was a real disappointment as far as the R experience goes.

Again,
Thanks

greg


On 3 Feb 2020, at 09:58, Ege Rubak <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. I think you need to search for help on installation of R and R packages in the Anaconda community. If you just need to use R and spatstat I would recommend that you simply install the official R.app from https://cran.r-project.org/bin/macosx/ and possibly RStudio<https://rstudio.com/> as an IDE. This is well tested and usually works without any problems.

I'm going to close this now since there isn't much we can do to help with the situation.

**Comment by rubak** [comment]
Glad it works. I bumped into a post discussing some of the problems you have seen and how to manage R packages through conda. I will leave it as a reference for other conda users in case it is useful:
https://community.rstudio.com/t/why-not-r-via-conda/9438/4

**Comment by gkinglisboa** [comment]
Ege,

One further thing I discovered is that the R being used in Anaconda is version 3.6.1.  But the R installed by homebrew is 3.6.2.  Maybe that gets closer to the problem (or not).


On 3 Feb 2020, at 10:53, Ege Rubak <notifications@github.com<mailto:notifications@github.com>> wrote:


Glad it works. I bumped into a post discussing some of the problems you have seen and how to manage R packages through conda. I will leave it as a reference for other conda users in case it is useful:
https://community.rstudio.com/t/why-not-r-via-conda/9438/4

**Comment by gkinglisboa** [comment]
Dear Ege,

Since this issue is closed, I don't know if you will see this email.  But I wanted to ask if you were aware of anyone using spatstat to analyse satellite wind and rain fields?  I am, and after a long time of exploring the data (correlating the two satellite fields) I started developing some point pattern analysis tools.  But I did not know what to call it.  Recently I came across Ripley's K etc and started reading up on point pattern analysis.  That brings me to finally starting to come to grips with the spatstat package.  All the examples that I have come across are in ecology and (maybe?) economics, but nothing on physics.  If so, then please let me know and if you know, please let me know if there are any others in meteorology and physics that are using spatstat.

greg


On 3 Feb 2020, at 12:31, Greg King <gking.lisboa@outlook.com<mailto:gking.lisboa@outlook.com>> wrote:

Ege,

One further thing I discovered is that the R being used in Anaconda is version 3.6.1.  But the R installed by homebrew is 3.6.2.  Maybe that gets closer to the problem (or not).


On 3 Feb 2020, at 10:53, Ege Rubak <notifications@github.com<mailto:notifications@github.com>> wrote:


Glad it works. I bumped into a post discussing some of the problems you have seen and how to manage R packages through conda. I will leave it as a reference for other conda users in case it is useful:
https://community.rstudio.com/t/why-not-r-via-conda/9438/4

**Comment by rubak** [comment]
Maybe @baddstats can remember people in physics and/or meteorology using spatstat. You could have a look at [papers that cite the old spatstat journal reference](https://scholar.google.com/scholar?cites=14298635295009907295) or [the ones that cite the spatstat book.](https://scholar.google.com/scholar?cites=12014572585326199922)

As you point out a lot of references appear to come from ecology, but also quite a few come from medicine. More surprisingly there is also [a paper about improving user passwords](https://www.scienceopen.com/hosted-document?doi=10.14236/ewic/HCI2008.12)...

Also there is [a paper in Optics Letters](https://www.osapublishing.org/ol/abstract.cfm?uri=ol-34-4-401) which must be closer to physics.

Finally, a classic point process paper motivated by cosmology is 
*J. Neyman and E.L. Scott. A statistical approach to problems of cosmology. Journal of the Royal Statistical Society, Series B, 20:1–43, 1958.*
