### ISSUE TITLE
`weighted.median()` with equal weights

### ISSUE THREAD

**Issue by wibeasley** [spatstat/spatstat#128]
There might be a problem with `weighted.median()`, as described in https://stackoverflow.com/q/60366677/1082435.  Please see @AllanCameron [dissection & answer](https://stackoverflow.com/a/60367567/1082435)

``` r
x <- c(10, 11, 12)
w <- c( 1,  1,  1)

spatstat::weighted.median(x, w)
#> [1] 10.5
spatstat::weighted.quantile(x, w, probs = .5)
#>  50% 
#> 10.5


matrixStats::weightedMedian(x, w)
#> [1] 11
median(x)
#> [1] 11
```

<sup>Created on 2020-02-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by baddstats** [comment]
There is a more fundamental issue here about the definition of a quantile (including the median) in small finite samples.

The help file for the R base function <code>quantile.default</code> says that there is an argument <code>type</code>, with 7 different options, which will give different answers. These are carefully described in a fine article by Rob Hyndman, cited in the help file. The default for <code>quantile.default</code> is <code>type=7</code>.

The algorithm in <code>spatstat::weighted.quantile</code> performs the analogue of <code>type=4</code> (according to its help file); that is, the cumulative distribution function F(x) is linearly interpolated and then the inverse function is computed. This algorithm is correctly implemented in the spatstat code.

The weighted median in the other package you mentioned is computing a different definition of the weighted median.

Thank you very much for drawing our attention to this example. This may prompt us to extend the implementation of <code>spatstat::weighted.median</code> to embrace the other types.

**Comment by baddstats** [comment]
Since `spatstat`has been split into sub-packages, the function in question is now `spatstat.geom::weighted.median` in the package `spatstat.geom`.

**Comment by baddstats** [comment]
This has been transferred to an issue for`spatstat.core`: see spatstat/spatstat.core/#4
