### ISSUE TITLE
options to control the quadscheme have no effect in mppm

### ISSUE THREAD

**Issue by robertaue** [spatstat/spatstat#129]
rm(list=ls())
library(spatstat)
data("demohyper")

res1 <- mppm(Points ~ Image, data=demohyper) # default setting
print(quad.mppm(res1)[[1]]) # quadrature scheme: 32 x 32

res2 <- mppm(Points ~ Image, nd=64, data=demohyper) # try to increase number of quad points
print(quad.mppm(res2)[[1]]) # nd did not change the qudadrature scheme!

**Comment by baddstats** [comment]
Thanks for noticing this.

It will be fixed shortly.

In the meantime, you can just create the quadrature schemes manually (as an extra column in the hyperframe) and then fit the model to these quadrature schemes.  Example:

    h <- demohyper
    h$Q <- solapply(h$Points, quadscheme, nd=128)
    res3 <- mppm(Q ~ Image, data=h)

**Comment by robertaue** [comment]
Oh great, that works well.

And many thanks for the fantastic spatstat package :)

**Comment by baddstats** [comment]
This is now fixed, in development version `spatstat 1.63-3.005` and later versions
