### ISSUE TITLE
object 'SpatstatVersion' not found

### ISSUE THREAD

**Issue by HackerMD** [spatstat/spatstat#13]
I'll get the following error calling `profilepl` and `mppm` functions within a custom package:

```
Error in get(name, envir = .spEnv) : object 'SpatstatVersion' not found
Calls: <Anonymous> ... versionstring.spatstat -> getSpatstatVariable -> get
```

**Comment by rubak** [comment]
Are you calling these functions without loading spatstat first? I think the environment `.spEnv` is generated when the spatstat package is loaded. Therefore the following will generate the error you are experiencing: `spatstat::versionstring.spatstat()`. Is it possible for you to load the package (e.g. via `require(spatstat)`) or do you need a workaround?

**Comment by HackerMD** [comment]
I'm using `Imports` in the `DESCRIPTION` file of my package and then call *spatstat* functions using the full namespace, e.g. `spatstat::mppm()`.
Of note, this works for some *spatstat* objects, such as `spatstat::ppp()`.

I would like to avoid using `require(spatstat)` within my package. What would you recommend?

**Comment by HackerMD** [comment]
Attaching the *spatstat* package via `library(spatstat)` in the main script that calls function of my custom package solved the problem. The user of my package shouldn't have to attach the *spatstat* package, however, but only my custom package (which depends on *spatstat*).

**Comment by HackerMD** [comment]
Including *spatstat* in `Depends` in the `DESCRIPTION` file also solves the problem. But I think it would be nicer if *spatstat* would use namespaces consistently.

**Comment by baddstats** [comment]
<code>spatstat:::versionstring.spatstat</code> is meant to give the version number of the *currently loaded* version of <code>spatstat</code>. I'll make a workaround for the case where <code>spatstat</code> is not loaded.

**Comment by baddstats** [comment]
This problem has been fixed in the current development version (1.44-1.016). Please try this out with your custom package and let us know if it is satisfactory.

**Comment by HackerMD** [comment]
Using the development version, I get

```
Error in do.call("ppm", append(list(...), list(rbord = rbord, justQ = TRUE)), : could not find function "ppm"
```

The namespace problem also affects other functions, in my case `profilepl()`.

**Comment by baddstats** [comment]
In `spatstat` development version **1.44-1.020** we have fixed this latest problem. 

If you still encounter namespace problems using this version, then your package effectively requires the `spatstat` namespace to be imported. I'd suggest that your package `DESCRIPTION` file should declare that it **Imports: spatstat**, and the `NAMESPACE` file should declare either

> `import(spatstat)`

or at least

> `importFrom(spatstat, ppm, profilepl, etc, etc, etc)`

including the names of all the `spatstat` functions that are needed to prevent namespace problems.

**Comment by HackerMD** [comment]
Putting `import(spatstat)` in the `NAMESPACE` file did the trick. Thanks!
