### ISSUE TITLE
Suggested edit to maptools::as.im.RasterLayer

### ISSUE THREAD

**Issue by rsbivand** [spatstat/spatstat#132]
Posted on https://stat.ethz.ch/pipermail/r-sig-geo/2020-June/028219.html; any objections?

**Comment by rubak** [comment]
Thanks for letting us know. The proposed function doesn’t work for general
factor valued rasters, so I have made another suggestion. My version works
for the test case below, which the original proposal does not.

Will you report back on r-sig-geo and recommend an update of maptools once
you have it in there?

## Function definition

``` r
as.im.RasterLayer <- function(from) 
{
  if (!requireNamespace("spatstat", quietly = TRUE))
    stop("package spatstat required for coercion")
  if (!requireNamespace("raster", quietly = TRUE))
    stop("package raster required for coercion")
  if (!raster::hasValues(from)) stop("values required in RasterLayer object")
  if (raster::rotated(from)) {
    stop("\n Cannot coerce because the object is rotated.\n Either coerce to SpatialPoints* from\n or first use the \"rectify\" function")
  }
  rs <- raster::res(from)
  orig <- bbox(from)[, 1] + 0.5 * rs
  dm <- dim(from)[2:1]
  xx <- unname(orig[1] + cumsum(c(0, rep(rs[1], dm[1]-1))))
  yy <- unname(orig[2] + cumsum(c(0, rep(rs[2], dm[2]-1))))
  ## Use `from` to make a vector `val` with input values
  val <- raster::values(from)
  if(is.factor(from)){
    lev <- levels(from)
    val <- factor(val, levels = lev[[1]]$ID, labels = lev[[1]]$VALUE)
  }
  ## Assign dimensions to `val` as a matrix in raster (European) layout:
  dim(val) <- dim(from)[1:2]
  ## Transform to spatstat format
  val <- spatstat::transmat(val, from = "European", to = "spatstat")
  im <- spatstat::im(val, xcol=xx, yrow=yy)
  return(im)
}
```

## Test case with NA, a non-used factor level and non-alphabetical level order

``` r
library(raster)
#> Loading required package: sp
r <- raster(nrow=2, ncol=3)
f <- factor(c(NA, letters[2:ncell(r)]),
            levels = rev(letters[1:ncell(r)]))
values(r) <- f
plot(r)
```

![](https://i.imgur.com/iaPyJyl.png)

``` r
levels(r)
#> [[1]]
#>   ID VALUE
#> 1  1     f
#> 2  2     e
#> 3  3     d
#> 4  4     c
#> 5  5     b
#> 6  6     a

i <- as.im.RasterLayer(r)
plot(i)
```

![](https://i.imgur.com/bl1WlpX.png)

**Comment by rubak** [comment]
Note: I had a mistake in the first version of the code snippet above, but it is fixed now and should be ready to use, but more extensive testing is welcome.

**Comment by matthewlewis896** [comment]
Hi @rubak thanks for generalising this - I admit I hadn't tested my solution too heavily before I sent it to r-sig-geo.

I've tried your solution and it seems to work for a few cases I've put to it, testing with masked rasters, etc.

One issue currently is that if a raster if made into a factor with `as.factor()` instead of changing the values, it doesn't gain the `$VALUE` column, `$ID` just becomes factor valued. Equally a common solution to making a raster factor valued seems to be:

```
library(raster)
#> Loading required package: sp

r <- raster(nrow=2, ncol=3)
r <- as.factor(r)
f <- levels(r)[[1]]
f$name <- c("vector", "of", "values")
levels(r) <- f
```
Which would give you a second column in levels called `$name` instead of `$VALUE`.

An alternative to specifying the column `$VALUE` would be to let it be the last column of levels, such that this bit of your function:
```
if(is.factor(from)){
    lev <- levels(from)
    val <- factor(val, levels = lev[[1]]$ID, labels = lev[[1]]$VALUE)
  }
```
becomes
```
if(is.factor(from)){
    lev <- levels(from)
    val <- factor(val, levels = lev[[1]]$ID, labels = unlist(lev[[1]][length(lev[[1]])]))
  }
```
Or something could be written where the user specifies the column they intend.

Cheers,
Matt

**Comment by rubak** [comment]
Hi @matthewlewis896 thanks for your input.

I don’t use `raster` much, so I’m just learning along the way.

### New function definition

``` r
as.im.RasterLayer <- function(from) 
{
  if (!requireNamespace("spatstat", quietly = TRUE))
    stop("package spatstat required for coercion")
  if (!requireNamespace("raster", quietly = TRUE))
    stop("package raster required for coercion")
  if (!raster::hasValues(from)) stop("values required in RasterLayer object")
  if (raster::rotated(from)) {
    stop("\n Cannot coerce because the object is rotated.\n Either coerce to SpatialPoints* from\n or first use the \"rectify\" function")
  }
  rs <- raster::res(from)
  orig <- bbox(from)[, 1] + 0.5 * rs
  dm <- dim(from)[2:1]
  xx <- unname(orig[1] + cumsum(c(0, rep(rs[1], dm[1]-1))))
  yy <- unname(orig[2] + cumsum(c(0, rep(rs[2], dm[2]-1))))
  ## Use `from` to make a vector `val` with input values
  val <- raster::values(from)
  if(is.factor(from)){
    lev <- levels(from)[[1]]
    val <- factor(val, levels = lev$ID, labels = lev[[length(lev)]])
  }
  ## Assign dimensions to `val` as a matrix in raster layout:
  dim(val) <- dm
  ## Transform to spatstat format
  val <- spatstat::transmat(val, from = list(x="-i", y="j"), to = "spatstat")
  im <- spatstat::im(val, xcol=xx, yrow=yy)
  return(im)
}
```

It is even possible to have a levels object in `raster` with more than two columns (e.g. `ID`, `VALUSE`, `name`).
Do you think this is something we will encounter in the wild or can we ignore
it (it will work, but always use the last column)?

Btw. do you know why the plot method for raster doesn’t use the factor names?

### Test case with NA, a non-used factor level and non-alphabetical level order

``` r
library(raster)
#> Loading required package: sp
r <- raster(nrow=2, ncol=3)
f <- factor(c(NA, letters[2:ncell(r)]),
            levels = rev(letters[1:ncell(r)]))
values(r) <- f
plot(r)
```

![](https://i.imgur.com/tEB3NXF.png)

``` r
levels(r)
#> [[1]]
#>   ID VALUE
#> 1  1     f
#> 2  2     e
#> 3  3     d
#> 4  4     c
#> 5  5     b
#> 6  6     a
i <- as.im.RasterLayer(r)
plot(i)
```

![](https://i.imgur.com/XHqP0Au.png)

### Test case without explicit factor names

``` r
rr <- raster(nrow=2, ncol=3)
values(rr) <- 1:6
rr <- as.factor(rr)
levels(rr)
#> [[1]]
#>   ID
#> 1  1
#> 2  2
#> 3  3
#> 4  4
#> 5  5
#> 6  6
plot(rr)
```

![](https://i.imgur.com/rGjZOBP.png)

``` r
ii <- as.im.RasterLayer(rr)
plot(ii, valuesAreColours = FALSE)
```

![](https://i.imgur.com/agxueLt.png)

``` r
ii
#> factor-valued pixel image
#> factor levels:
#> [1] "1" "2" "3" "4" "5" "6"
#> 2 x 3 pixel array (ny, nx)
#> enclosing rectangle: [-180, 180] x [-90, 90] units
```

### Test case with alternative name for factor level column

``` r
rrr <- rr
f <- levels(rrr)[[1]]
f$name <- c("vector", "of", "values")
levels(rrr) <- f
levels(rrr)
#> [[1]]
#>   ID   name
#> 1  1 vector
#> 2  2     of
#> 3  3 values
#> 4  4 vector
#> 5  5     of
#> 6  6 values
plot(rrr)
```

![](https://i.imgur.com/SpPX62M.png)

``` r
iii <- as.im.RasterLayer(rrr)
plot(iii, valuesAreColours = FALSE)
```

![](https://i.imgur.com/fBVeLUU.png)

``` r
iii
#> factor-valued pixel image
#> factor levels:
#> [1] "vector" "of"     "values"
#> 2 x 3 pixel array (ny, nx)
#> enclosing rectangle: [-180, 180] x [-90, 90] units
```

**Comment by matthewlewis896** [comment]
No idea why plot in raster leaves it out unfortunately but agree it's an annoying feature.

I think while you can have multiple columns this is going to be so rare we could almost definitely leave it out provided it's mentioned in the docs.

Equally though, we could specify:

``` {r}
as.im.RasterLayer <- function(from, factor.col.name = NULL) 
{
  if (!requireNamespace("spatstat", quietly = TRUE))
    stop("package spatstat required for coercion")
  if (!requireNamespace("raster", quietly = TRUE))
    stop("package raster required for coercion")
  if (!raster::hasValues(from)) stop("values required in RasterLayer object")
  if (raster::rotated(from)) {
    stop("\n Cannot coerce because the object is rotated.\n Either coerce to SpatialPoints* from\n or first use the \"rectify\" function")
  }
  rs <- raster::res(from)
  orig <- bbox(from)[, 1] + 0.5 * rs
  dm <- dim(from)[2:1]
  xx <- unname(orig[1] + cumsum(c(0, rep(rs[1], dm[1]-1))))
  yy <- unname(orig[2] + cumsum(c(0, rep(rs[2], dm[2]-1))))
  ## Use `from` to make a vector `val` with input values
  val <- raster::values(from)
  if(is.factor(from)){
    lev <- levels(from)[[1]]
    if(!is.null(factor.col.name)){
        factor.col <- which(colnames(lev) == factor.col.name)
    }else{
        factor.col <- length(lev)
    }
    val <- factor(val, levels = lev$ID, labels = lev[[factor.col]])
  }
  ## Assign dimensions to `val` as a matrix in raster layout:
  dim(val) <- dm
  ## Transform to spatstat format
  val <- spatstat::transmat(val, from = list(x="-i", y="j"), to = "spatstat")
  im <- spatstat::im(val, xcol=xx, yrow=yy)
  return(im)
}
```

So for:

``` {r}
library(raster)
rr <- raster(nrow=2, ncol=3)
values(rr) <- 1:6
rr <- as.factor(rr)

rrr <- rr
f <- levels(rrr)[[1]]
f$name <- c("vector", "of", "values")
f$name2 <- letters[1:6]
levels(rrr) <- f
levels(rrr)
[[1]]
  ID   name name2
1  1 vector     a
2  2     of     b
3  3 values     c
4  4 vector     d
5  5     of     e
6  6 values     f
```

We could get:

``` {r}
iii <- as.im.RasterLayer(rrr)
plot(iii)
```

![test](https://user-images.githubusercontent.com/54063056/88484392-20ac5480-cf66-11ea-90aa-45a82b028173.png)


Or we could get:

``` {r}
iv <- as.im.RasterLayer(rrr, factor.col.name = "name")
plot(iv)
```

![test2](https://user-images.githubusercontent.com/54063056/88484458-69640d80-cf66-11ea-9907-c42bacc24c15.png)

Which do you think is better? Also possible to add more useful error message in case of column mis-specification (currently it's this).

``` {r}
v <- as.im.RasterLayer(rrr, factor.col.name = "names")
 Error in .subset2(x, i, exact = exact) : 
  attempt to select less than one element in get1index 
```

But could add something like:

``` {r}
as.im.RasterLayer <- function(from, factor.col.name = NULL) 
{
  if (!requireNamespace("spatstat", quietly = TRUE))
    stop("package spatstat required for coercion")
  if (!requireNamespace("raster", quietly = TRUE))
    stop("package raster required for coercion")
  if (!raster::hasValues(from)) stop("values required in RasterLayer object")
  if (raster::rotated(from)) {
    stop("\n Cannot coerce because the object is rotated.\n Either coerce to SpatialPoints* from\n or first use the \"rectify\" function")
  }
  rs <- raster::res(from)
  orig <- bbox(from)[, 1] + 0.5 * rs
  dm <- dim(from)[2:1]
  xx <- unname(orig[1] + cumsum(c(0, rep(rs[1], dm[1]-1))))
  yy <- unname(orig[2] + cumsum(c(0, rep(rs[2], dm[2]-1))))
  ## Use `from` to make a vector `val` with input values
  val <- raster::values(from)
  if(is.factor(from)){
    lev <- levels(from)[[1]]
    if(!is.null(factor.col.name)){
        if(factor.col.name %in% colnames(lev)){
            factor.col <- which(colnames(lev) == factor.col.name)
        } else {
            stop("'factor.col.name' is not a column name of the raster 'from'")
        }
    }else{
        factor.col <- length(lev)
    }
    val <- factor(val, levels = lev$ID, labels = lev[[factor.col]])
  }
  ## Assign dimensions to `val` as a matrix in raster layout:
  dim(val) <- dm
  ## Transform to spatstat format
  val <- spatstat::transmat(val, from = list(x="-i", y="j"), to = "spatstat")
  im <- spatstat::im(val, xcol=xx, yrow=yy)
  return(im)
}
```

Which then gives you:

``` {r}
v <- as.im.RasterLayer(rrr, factor.col.name = "names")
Error in as.im.RasterLayer(rrr, factor.col.name = "names") : 
  'factor.col.name' is not a column name of the raster 'from'
```

**Comment by rubak** [comment]
Thanks @matthewlewis896 I think the last function you give above is a good candidate for inclusion in `maptools` if @rsbivand agrees? In particular it depends whether or not the extra argument `factor.col.name` in the signature is a nuisance. The other `as.im` function in `maptools` (`as.im.SpatialGridDataFrame`) has `from` as only argument, but in `spatstat` the generic signature is `as.im(X, ...)`. Otherwise the version without `factor.col.name` is fine also.

Also, @rsbivand do you want the test cases above to be written out as tests for inclusion in `maptools` with some numerical checks rather than the graphical checks performed above?

**Comment by rsbivand** [comment]
I can look at getting the signature consistent, should be OK. And yes, numerical tests could be added to the examples, though in examples plots are OK too. Once you both confirm that we are ready to go, I'll make the edits to maptools and move towards CRAN submission (after their summer break).

**Comment by rubak** [comment]
Sounds great @rsbivand. It is a go from me. You are of course right that the test cases above could just go in the examples with plots and everything. Then I don't think we should bother with writing numerical tests. Let me know if you want me to do anything else. What about you @matthewlewis896 are you OK with @rsbivand putting this version of our code in `maptools`?

**Comment by matthewlewis896** [comment]
Thanks @rubak @rsbivand I'm also happy to go ahead. Let me know if you want me to do anything else also.

**Comment by rsbivand** [comment]
I'll report back here when the edit has been added to **maptools** on R-Forge for you to check before I submit.

**Comment by rsbivand** [comment]
Committed to R-Forge, rev. 371. Please download and test from https://r-forge.r-project.org/R/?group_id=943 or install.packages("maptools", repos="http://R-Forge.R-project.org") once the build of rev. 371 completes. Please suggest an argument description for `factor.col.name`.

**Comment by matthewlewis896** [comment]
How about:

column name of `from` to be treated as a factor; if NULL defaults to last column of `from`. Not used if `from` is not a factor.

**Comment by rsbivand** [comment]
OK, thanks, in rev. 374. @matthewlewis896 I added you to contributors, is that OK with you?

**Comment by matthewlewis896** [comment]
That's great, thanks very much @rsbivand!

**Comment by rubak** [comment]
Sounds great @rsbivand. If you need my ORCID it's 0000-0002-6675-533X.

Btw. maybe the description should be slightly modified:

column name of `levels(from)` to be treated as a factor; if `NULL` defaults to last column of from. Ignored if `from` is not a raster with factor values.

**Comment by matthewlewis896** [comment]
Agree that's a bit clearer, thanks @rubak

**Comment by rsbivand** [comment]
Current at rev. 376. Will submit when CRAN comes back from their summer break.

**Comment by baddstats** [comment]
Thank you, everyone!
