### ISSUE TITLE
Multitype Marked ppp scan.test

### ISSUE THREAD

**Issue by celsomilne** [spatstat/spatstat#134]
Is it possible to do a `spatstat::scan.test` on a multitype `ppp`? I know, of course, that you can do it on a 2-type marked point pattern:

```R
> P <- ppp(x=runif(100), y=runif(100), marks=factor(runif(100) >= 0.5))
> scan.test(P, method="binomial", alternative="two.sided", nsim=100, r=0.1)
```

But, now, let's say I adjust P so that its marks multi-type instead:

```R
> marks(P) <- factor(round(runif(100, min=0, max=3)))
```

I now want to run a scan.test on each combination of marks. Is there a way of doing this without just using a nested for loop?

I've browsed the documentation (rather thoroughly) and haven't found any way of doing this. Of course, my first thought was to use `alltypes`, but `htest` objects cannot be cast to `fv`:

```R
> alltypes(P, fun=scan.test, r=0.1)
Error in UseMethod("as.fv") : 
  no applicable method for 'as.fv' applied to an object of class "c('scan.test', 'htest')"
```

I guess this issue is a placeholder for a feature request for multi-type hypothesis testing.

**Comment by baddstats** [comment]
You also asked this question on Stackoverflow. I will answer it on Stackoverflow because the Issues page is intended for bugs and software problems, not general queries.
