### ISSUE TITLE
Envelopes not produced for Lcross.inhom from GAM with correction = "none"

### ISSUE THREAD

**Issue by coreydevinanderson** [spatstat/spatstat#135]
It seems that there is something up with plotting (or producing) a significance envelope for Lcross.inhom() via lambdaX = TRUE from a GAM  with correction = "none". It works fine for Linhom() and when correction is not specified as "none" in the call to envelope(). 

My reproducible example below is based on window sampling; however, my data sets are based on a small world model, so I would like to opt out of correction.

I should also state that my intention here was to use the GAM as an alternative to a multitype inhomogeneous Poisson point process model (as a means to correct the cross-type summary function for inhomogeneity) because some of the effects are not loglinear. I am not entirely sure if the interaction terms (with the marks) present theoretical issues or not in the context of ppm with use.gam = TRUE. I am more interested here in prediction for the sake of correction (than testing, per se).

# Reproducible example

library(spatstat)
library(splines)

ppp_1 <- rpoispp(function(x,y){5*abs(sin(x))}, win = square(3*pi))
ppp_2 <- rpoispp(function(x,y){5*abs(sin(x))}, win = square(3*pi))

f <- function(x,y){5*abs(sin(x))}
im_sin <- as.im(f, W = square(3*pi))

multi_ppp <- superimpose(A = ppp_1, B = ppp_2)

my_gam <- ppm(multi_ppp ~ bs(im_sin, 3)*marks, use.gam = TRUE)

# For comparison
my_Lcross_env0 <- envelope(multi_ppp, Lcross, global = TRUE, nsim = 39)
plot(my_Lcross_env0)

# Compare envelope with and without correction = "none"
my_Lcross_env1 <- envelope(my_gam, Lcross.inhom, lambdaX = my_gam, global = TRUE, nsim = 39, fix.n = TRUE)
my_Lcross_env2 <- envelope(my_gam, Lcross.inhom, lambdaX = my_gam, global = TRUE, nsim = 39, fix.n = TRUE, correction = "none")

plot(my_Lcross_env0)
plot(my_Lcross_env1)
plot(my_Lcross_env2)

**Comment by baddstats** [comment]
Thank you for alerting us. 

In the object `my_Lcross_env2`, the upper and lower limits of the envelope (`lo`, `hi`) are identical to the mean simulated value (`mmean`). So the envelope is there, but has zero width.

 I will investigate.

**Comment by baddstats** [comment]
Easy. The option `correction="none"` was accepted but not implemented, so that the resulting object did not contain a column of values of the uncorrected estimate.

A fix will be uploaded shortly in `spatstat 1.64-0.023`.
