### ISSUE TITLE
 anova.mppm: likelihood ratio test does not work for random effects models for replicated patterns.

### ISSUE THREAD

**Issue by marcelinodelacruz** [spatstat/spatstat#136]
Including a random term in the models of the example of `anova.mppm()` makes  the likelihood ratio test to fail, e.g.: 
 
 
 ```R   
 H <- hyperframe(X=waterstriders)
 #' test for loglinear trend in x coordinate
 mod0 <- mppm(X~1, data=H, Poisson(), random = ~1|id)
 modx <- mppm(X~x, data=H, Poisson(), random = ~1|id)
 anova(mod0, modx, test="Chi")
 ``` 
 
 >Error in anova.lme(structure(list(modelStruct = structure(list(reStruct = structure(list( : 
  objects must inherit from classes "gls", "gnls", "lm", "lmList", "lme", "nlme", "nlsList", or "nls"
Error in anova.mppm(mod0, modx, test = "Chi") : anova failed

**Comment by baddstats** [comment]
This has arisen because recent versions of `nlme` have imposed stricter restrictions on the arguments of  `anova.lme`. We are trying to find a work-around.

**Comment by baddstats** [comment]
As a temporary solution, if you set `spatstat.options(developer=TRUE)`, your example code will work, in the development version `spatstat 1.64-1.027`.

**Comment by marcelinodelacruz** [comment]
Thank you so much Adrian for dealing with this. Your temporary solution works fine also with other data and examples.

**Comment by baddstats** [comment]
This solution has been adopted permanently in `spatstat 1.64-1.052` and later.

So you do not need to type`spatstat.options(developer=TRUE)` any more.
