### ISSUE TITLE
Installation error: call: if (today - as.Date(rdate) > 365) {

### ISSUE THREAD

**Issue by andycraig** [spatstat/spatstat#139]
## Bugs

Hi, I encountered a surprising error while attempting to install the 'surveillance' package, which has 'spatstat' as a dependency:

```r
install.packages("surveillance")
```
 
```
Error in installing spatstat dependency:
** testing if installed package can be loaded
Error: package or namespace load failed for ‘spatstat’:
.onAttach failed in attachNamespace() for 'spatstat', details:
  call: if (today - as.Date(rdate) > 365) {
  error: missing value where TRUE/FALSE needed
```

This error seems to be occurring here: https://github.com/spatstat/spatstat/blob/2f169040f2129676505fdf521e757db583742d39/R/versions.R#L62-L69

I copied and ran some of those lines:

```r
rv <- R.Version()
rdate <- with(rv, ISOdate(year, month, day))
rdate
# [1] NA
```

`rdate` being `NA` causes an error in `if (today - as.Date(rdate) > 365)`.

The problem is that `R.Version()$year`, `R.Version()$month` and `R.Version()$day` are all `""`. This wasn't a system I set up, so I'm not sure how that might come about, but apparently it's possible.

I encountered this error using R 3.5.1 "Feather Spray". I installed R 3.6.3, and I was able to install spatstat as normal.

I found this report of what looks like the same problem: http://r-sig-geo.2731867.n2.nabble.com/spatstat-installation-td7593497.html So it sounds like it's rare but not totally unique to my system. It might be an R problem rather than a spatstat problem, but I thought I should let you know about it.

Thank you.

**Comment by rubak** [comment]
Thanks for pointing us to this peculiarity @andycraig . I think we should simply insert a check for `!is.na(rdate)` in future versions of spatstat.

**Comment by baddstats** [comment]
The offending code requires R version `3.6.0` or later, but the `spatstat` description file permits R version `3.3.0` or later. Since we are now at R version `4.0.2` it is probably OK to change the `spatstat` description file to require R version `3.6.0` rather than trying to work around this problem. (But I will also include a workaround as @rubak suggests).

**Comment by baddstats** [comment]
Fixed in `spatstat 1.64-1.032`

**Comment by rubak** [comment]
Is this the only reason to bump the R requirement from 3.3 to 3.6? I know 3.3 is old but historically we have had many users on e.g. university servers where software updates may be very hard to got through some IT admin. If the work around solves the problem for R 3.3 couldn't we leave the requirement as it was?

**Comment by baddstats** [comment]
OK, I will revert to requiring R>= 3.3.0

**Comment by andycraig** [comment]
@baddstats @rubak Thanks both!
