### ISSUE TITLE
Warning in (function (fmt, ...)  : argument not used by format

### ISSUE THREAD

**Issue by jfrench** [spatstat/spatstat#141]
R-devel has a new runtime check in sprintf() that all arguments are used by the format and this is showing one or more warnings in the check, usually in the examples.  E.g.

Warning in sprintf("%s$", extension, ignore.case = TRUE) :
   argument not used by format
Warning in sprintf("<a href='%s'>%s</a>", getFunctionLinks(tokens[w]), tokens[w],  :
   argument not used by format

I've been able to document the locations where the issues take place here: https://github.com/jfrench/files/blob/master/spatstat-Ex_x64.Rout

The easiest way to find the problematic examples is to search for: argument not used by format

**Comment by rubak** [comment]
Thanks. We are aware of the problem and investigating. Some of it arises when labels are made in `plot.fv`.

**Comment by baddstats** [comment]
Fixed (in development version 1.64-1.051 and later)
