### ISSUE TITLE
Drop `proglang` macro to maintain R 3.5 compatibility

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#142]
Should we drop the macro `\proglang` in {pairdist,crossdist}.lpp to maintain compatability with legacy R 3.5?

This macro is the only reason `R CMD check spatstat` fails on that platform as far as I can tell:

<https://github.com/spatstat/spatstat/runs/1371518392?check_suite_focus=true#step:11:149>

On the other hand I guess this will only effect the layout of the help file on a system with R 3.5, so we can also leave it as it is.

**Comment by baddstats** [comment]
Done
