### ISSUE TITLE
Vmark does not work with normalise=T and X with single mark (eg. only DBH)

### ISSUE THREAD

**Issue by pavel-fibich** [spatstat/spatstat#143]
To reproduce on spruces dataset available in spatstat just call:
```
> Vmark(spruces,normalise = T)
Error in sig2[i, i] : incorrect number of dimensions
```
It is because, in the Vmark code there is
 ``sig2 <- var(marks(X))``
that produces single number if X has only single mark (eg. DBH). And bellow you have
```
if (normalise) 
            Vi <- eval.fv(Vi/sig2[i, i])
```
that expects more complicated/matrix structure. It can be corrected by
```
if (normalise) 
            Vi <- eval.fv(Vi/ifelse(is.matrix(sig2),sig2[i,i],sig2))
```
Best regards, Pavel

**Comment by baddstats** [comment]
Thank you for spotting this bug. It has been fixed in the development version (`spatstat` versions `1.64-3.015` and later).
