### ISSUE TITLE
New method for as.linnet

### ISSUE THREAD

**Issue by agila5** [spatstat/spatstat#145]
Dear `spatstat` developers, first of all, thank you very much for your work on this package (that I use almost every day). I created this github issue since I would like to ask you a question. I'm working on the R package [`sfnetworks`](https://github.com/luukvdmeer/sfnetworks), and I defined a new method to convert `sfnetworks` object into `linnet` class. It works as follows: 

``` r
# Install sfnetworks with 
remotes::install_github("luukvdmeer/sfnetworks")
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'sfnetworks' from a github remote, the SHA1 (3cafc6a3) has not changed since last install.
#>   Use `force = TRUE` to force installation

# load raw data and convert into sfnetworks format with projected coordinates
data("roxel", package = "sfnetworks")
roxel_sfn <- sf::st_transform(sfnetworks::as_sfnetwork(roxel), 3035)
par(mar = rep(0, 4))
plot(roxel_sfn)
```

![](https://i.imgur.com/XwWQGvh.png)

``` r

# extract vertices and convert into ppp format
roxel_vertices_ppp <- spatstat::as.ppp(sf::st_as_sf(roxel_sfn, "nodes"))

# extract edge-list
roxel_edge_list <- as.matrix(
  (as.data.frame(sfnetworks::activate(roxel_sfn, "edges")))[, c("from", "to")]
)

# build linnet
roxel_linnet <- spatstat::linnet(
  vertices = roxel_vertices_ppp,
  edges = roxel_edge_list,
  sparse = TRUE
)
#> Warning: Duplicated segments were ignored
plot(roxel_linnet, main = "", col = "lightgrey")
```

![](https://i.imgur.com/l5cGNVe.png)

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Would you accept a PR that adds a new method to `as.linnet`? Otherwise, I could add the code to the [`sfnetworks`](https://github.com/luukvdmeer/sfnetworks) package.

**Comment by baddstats** [comment]
Thank you for offering this code (and for the enouragement about `spatstat`!).

Yes it could be included in `spatstat`, if we can figure out how to do this without having to "Suggest" the `sfnetworks` package. (CRAN have asked us not to increase the number of packages which are "Suggest"-ed by `spatstat`). 

I notice that `sfnetworks` already Suggests `spatstat`, so maybe the simplest solution would be to include the code in `sfnetworks`.

**Comment by agila5** [comment]
Dear Prof. Baddeley, thank you very much for your answer. I implemented the new `as.linnet.sfnetwork` method in the `sfnetworks` repository: https://github.com/luukvdmeer/sfnetworks/pull/101
