### ISSUE TITLE
Bug in `inradius()` for rectangular windows

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#148]
Reported by Frédéric Lavancier:

The function `inradius` is wrong for rectangular windows. 
Should be (like in `incircle`) : 
```r
xr <- W$xrange
yr <- W$yrange
radius <- min(diff(xr), diff(yr))/2
```
instead of 
```r
diameter(W)/2
```
Example:
```r
> inradius(square(1))
[1] 0.7071068
```
vs.
```r
> incircle(square(1))
$x
[1] 0.5

$y
[1] 0.5

$r
[1] 0.5
```

**Comment by baddstats** [comment]
D'oh

I will fix this in `spatstat.geom` rather than the old `spatstat`.
