### ISSUE TITLE
Irregular window in idw function

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#15]
When `idw` is used on a point pattern with non-rectangular window the result is returned in the entire frame of the window. Is there a reason to have this behaviour? If so, we should include an example of extracting the relevant region of the returned image(s) in the help file. See http://stackoverflow.com/q/35617548/3341769 for an example.

**Comment by baddstats** [comment]
That's a bug - it should behave like density.ppp and return an image in the same window as the original data. I will fix it immediately.
