### ISSUE TITLE
 object ‘markvario’ is not exported by 'namespace:spatstat'

### ISSUE THREAD

**Issue by stela2502** [spatstat/spatstat#150]
This is clearly a bug as the restructuring of the package obviously also removed some function.

This simple line of code throws the error and [this github issue](https://github.com/satijalab/seurat/issues/4226#issuecomment-799931946) explains the fix. The problem is clearly associated with a version change of the spatstat package.

```
install.packages('Seurat')
```

 It would be terrific if you could fix this.

**Comment by rubak** [comment]
I'm sorry, but this is not a bug. The function has been moved to a sub package and the maintainer of `Seurat` has been informed and needs to update the package. The error will go away when this is done. Did you report the error to the maintainer?

**Comment by stela2502** [comment]
Sorry - I have seen that only a little later.
So it is the Seurat people that need to act now.
This is a really problem if the software (Seurat in this case) does not get tested enough.
Even against all the other updated packages.

I have to admit that I also do not do this on a regular basis.

**Comment by stela2502** [comment]
I copied your text into the Seurat Issue. Thank you for your time!
