### ISSUE TITLE
object ‘CDF’ is not exported by 'namespace:spatstat'

### ISSUE THREAD

**Issue by PavoDive** [spatstat/spatstat#151]
I'm posting this issue here, although I'm not absolutely sure it belongs to spatstat. Perhaps it does, because of backward compatibility.

While trying to `install.packages("OutlierDetection")` in a linux (Ubuntu) machine, I got the following error:

```
Error: object ‘CDF’ is not exported by 'namespace:spatstat'
Execution halted
ERROR: lazy loading failed for package ‘OutlierDetection’
* removing ‘/usr/local/lib/R/site-library/OutlierDetection’
```

I posted an almost identical copy of this issue to OutlierDetection, but the contributors to the repo are a CRAN's bot and (I think) the package creator, who has not been active in the last year.

**Comment by baddstats** [comment]
This requires action from the `OutlierDetection` package maintainer. 

 @rubak has provided a [github repository](https://github.com/rubak/spatstat.revdep) showing the changes that are required (for each package that depends on `spatstat`).

You say that the maintainer has not been active recently. Please contact them again and advise them to look at [github repository rubak/spatstat.revdep](https://github.com/rubak/spatstat.revdep).

If you do not get a response, we may consider sending a fix to CRAN.

**Comment by rubak** [comment]
@PavoDive In the meantime you can install a working version like this (beware that it downloads the entire git repo which is probably hundreds of MB and stores it in a temporary directory until you reboot):

```r
remotes::install_github("rubak/spatstat.revdep", subdir = "OutlierDetection")
```

**Comment by PavoDive** [comment]
@rubak  Thanks for your quick reply! I'll follow your advice, thank you.
