### ISSUE TITLE
'as.ppp' is not an exported object from 'namespace:spatstat'

### ISSUE THREAD

**Issue by eweaverdyck** [spatstat/spatstat#152]
I am having trouble coercing data into a ppp object in spatstat version 2.0.1.
Here is a reproducible example:
    library(spatstat)
    library(sf)
    x<-runif(10)
    y<-runif(10)
    test<-as.data.frame(cbind(x,y))
    names(test)<-c("x","y")
    data<-st_as_sf(test, coords=c("x","y"))
    data.ppp<-as.ppp(data)

This gives me:
    Error: 'as.ppp' is not an exported object from 'namespace:spatstat'

Looking into the NAMESPACE files, I found "as.ppp" as an exported object in the spatstat.geom (line 133), so I tried
    data.ppp<-spatstat.geom::as.ppp(data)
but got exactly the same error:
    Error: 'as.ppp' is not an exported object from 'namespace:spatstat'

Incidentally, I get a similar error when I try to use as.owin().
I am running R x64 4.04 on a Windows machine.
Thank you very much for your help.

**Comment by rubak** [comment]
Which version of `sf` are you running? Please try to update it first. Then everything should work. Let us know whether this solves the issue

**Comment by eweaverdyck** [comment]
yes, that worked! Updating sf from 0.9.7 to 0.9.8 did the trick. Thank you very much!

**Comment by sistia01** [comment]
Hello, I'm having a similar issues as the one described above. 

Error message: Error: 'ppp' is not an exported object from 'namespace:spatstat'

> packageVersion("sf")
[1] ‘1.0.4’

Running on macOS Monterey version 12.0.1 2GHz quad-core intel core i5 processor 

[1] "R version 4.0.5 (2021-03-31)"

**Comment by rubak** [comment]
Could you please supply a fully reproducible example? With recent versions of `sf` and `spatstat` there should be no problem.

**Comment by baddstats** [comment]
1. Update all your packages (not just `sf` but all packages that are installed, especially the `spatstat` family)
2. If you still get the error, type `traceback()` after the error, and cut-and-paste the traceback output here
3. Type `library(spatstat); sessionLibs()` and cut-and-paste the output here

**Comment by sistia01** [comment]
Full code: (package = Giotto)
trendSceek_output <- trendSceek(
  gobject = seqfish_mini,
  expression_values = c("normalized", "raw"),
  subset_genes = NULL,
  nrand = 100,
  ncores = 8)
using 'trendsceek' for spatial gene/pattern detection. If used in published research, please cite:
  Edsgard, Daniel, Per Johnsson, and Rickard Sandberg. 'Identification of Spatial Expression Trends in Single-Cell Gene Expression Data.'
          Nature Methods 15, no. 5 (May 2018): 339-42. https://doi.org/10.1038/nmeth.4634.
Error: 'ppp' is not an exported object from 'namespace:spatstat'

-------------

1. Ran update.packages(ask = FALSE)

2. > traceback()
stop(gettextf("'%s' is not an exported object from 'namespace:%s'", 
       name, getNamespaceName(ns)), call. = FALSE, domain = NA)
getExportedValue(pkg, name)
spatstat::ppp
trendsceek::pos2pp(spatial_locations)
trendSceek(gobject = seqfish_mini, expression_values = c("normalized", 
       "raw"), subset_genes = NULL, nrand = 100, ncores = 8)

3. > library(spatstat); sessionLibs()
Loading required package: spatstat.data
Loading required package: spatstat.geom
spatstat.geom 2.3-0
Loading required package: spatstat.core
Loading required package: nlme
Loading required package: rpart
spatstat.core 2.3-2
Loading required package: spatstat.linnet
spatstat.linnet 2.3-0

spatstat 2.2-0       (nickname: ‘That's not important right now’) 
For an introduction to spatstat, type ‘beginner’ 

Libraries loaded:
	 Biobase 2.50.0 
	 BiocGenerics 0.36.1 
	 Giotto 1.0.3 
	 nlme 3.1-153 
	 rpart 4.1-15 
	 spatstat 2.2-0 
	 spatstat.core 2.3-2 
	 spatstat.data 2.1-0 
	 spatstat.geom 2.3-0 
	 spatstat.linnet 2.3-0 
Libraries imported:
	 abind 1.4-5 
	 colorspace 2.0-2 
	 compiler 4.0.5 
	 crayon 1.4.2 
	 data.table 1.14.2 
	 deldir 1.0-6 
	 dplyr 1.0.7 
	 ellipsis 0.3.2 
	 fansi 0.5.0 
	 generics 0.1.1 
	 ggplot2 3.3.5 
	 glue 1.5.1 
	 goftest 1.2-3 
	 grid 4.0.5 
	 gtable 0.3.0 
	 lattice 0.20-45 
	 lifecycle 1.0.1 
	 magrittr 2.0.1 
	 Matrix 1.3-4 
	 mgcv 1.8-38 
	 munsell 0.5.0 
	 pillar 1.6.4 
	 pkgconfig 2.0.3 
	 polyclip 1.10-0 
	 purrr 0.3.4 
	 R6 2.5.1 
	 Rcpp 1.0.7 
	 rlang 0.4.12 
	 scales 1.1.1 
	 spatstat.sparse 2.0-0 
	 spatstat.utils 2.2-0 
	 splines 4.0.5 
	 tensor 1.5 
	 tibble 3.1.6 
	 tidyselect 1.1.1 
	 tools 4.0.5 
	 trendsceek 1.0.0 
	 utf8 1.2.2 
	 vctrs 0.3.8

**Comment by rubak** [comment]
The package `trendsceek` is outdated. The last update was almost 4 years ago and the package author has chosen not to put it on the official CRAN repository, so interoperability with other packages is not checked. It would be fairly easy to fix `trendsceek` to work with current versions of `spatstat`, but I don't know if the author is actively working on the package anymore. If you really need to use this for analysis I see these options:

1. Contact the author of `trendsceek` on GitHub and ask them to update the package (possibly help them identify what needs to be changed).
2. Fork `trendsceek` to your own GitHub account and make a few modifications so it works with recent versions of `spatstat`.
3. Install an old version of `spatstat` which works with `trendsceek`.

Option 3 is potentially a nightmare and I don't recommend it.

**Comment by wangqi770319** [comment]
Hello, I also encountered a similar problem as above, I need your help.
When running the program in the latest version of RStudio:
iInstall.package(“devtools”)
library(devtools)
install_github(“Zongzheng/forestSAS”)
library(spatstat)
library(forestSAS)
tree.pppX<-ppp(x=treedata$x,y=treedata$y,
window=owin(c(0,200),c(0,100)),marks=treedata[,c(1,4:8)])
tree.pppX
The above program works normally, but problems occur in the following programs:
nnindices<-nnIndex(tree.ppp,N=4,id=tree.ppp$marks$id,smark = c("sp.code","dbh.cm","storey","crownwid.m","group","biomass.kg","quality","x","y"),buffer=FALSE,buf.xwid=5,buf.ywid=5)
Error:  错误: 'ppp' is not an exported object from 'namespace:spatstat'
Please give me help to solve this problem, thank you very much!
