### ISSUE TITLE
Error when simulating determinantal point process

### ISSUE THREAD

**Issue by jbrehmer42** [spatstat/spatstat#154]
Dear `spatstat` developers, when I run the following code
```
set.seed(3)
DPPscale <- 0.1
DPPvar <- 8.5
dat <- simulate( dppGauss(lambda = DPPvar, alpha = DPPscale, d = 2), nsim = 100)
```
then the function `rdppp` throws the error

`The dimension differs from the number of columns in index`

This happens for the simulation 81/100 in `simulate.detpointprocfamily`. I think the reason is that the matrix in `indexlist[[81]]` created in `simulate.detpointprocfamily` has only one row. When `indexlist` is later passed to the function `rdpp`, then the line

`sampleindex <- as.matrix(index[rbinom(nrow(index), 1, eig)==1, ])`

changes the rows and columns of the matrix.

Thank you

**Comment by baddstats** [comment]
Thank you for telling us. 

I can reproduce the error.

This affects the sub-package `spatstat.core`, so I will transfer the issue to the repository for `spatstat.core`.
