### ISSUE TITLE
Bug in visual debugger of rmh ?

### ISSUE THREAD

**Issue by dschuhmacher** [spatstat/spatstat#155]
It appears the visual debugger in the function `rmh` does not display accepted births and deaths correctly, i.e. accepted births are not added to the **displayed** point pattern in the next step and accepted deaths are not deleted from it. For moves everything seems to work fine. The issue happens for me both on quartz- and x11-devices.

Minimal reproducible example:
`mod <- list(cif="strauss", par=list(beta=200, gamma=0.1, r=0.05), w=c(0,1,0,1))`
`cont <- list(p=0, q=0.5)`
`set.seed(44)`
`xi <- rmh(model=mod, start=list(n.start=1), control=cont, snoop = TRUE)`

Also, if we start with an empty point pattern (`n.start=0`), the visual debugger auto-exits after a single step. I presume it exits whenever it reaches the empty point pattern after the initial step.

**Comment by baddstats** [comment]
Thank you for pointing this out!
I will investigate.
This issue will be moved to the `spatstat.core` repository which is the new location of the `rmh` code.

**Comment by baddstats** [comment]
Redirected to https://github.com/spatstat/spatstat.core/issues/17#issue-1088058772

**Comment by baddstats** [comment]
Bug is fixed in `spatstat 2.3-2.004`. Please try it out!
