### ISSUE TITLE
I cannot update spatstat

### ISSUE THREAD

**Issue by AvolaAmg** [spatstat/spatstat#156]
Hi There, 

I am trying to update spatstat on my server (I need the latest version for Seurat). This is the type of error I get: 

update.packages("spatstat.data", lib = "/camp/lab/prieto-godinoll/working/Alida_Singlecell/scANALYSIS/R_libs")
Warning: unable to access index for repository spatstat.data/src/contrib:
  cannot open URL 'spatstat.data/src/contrib/PACKAGES'

I have no idea what to do to update this package. 

Thanks for your help, 
Alida

**Comment by baddstats** [comment]
This is not related to spatstat. The help for `update.packages` explains that you normally do not specify the names of the packages that you want to update; all installed packages will be updated. If you wanted to update only the package `spatstat.data` then you should find the directory (folder) which contains the installed `spatstat.data` package, and write the path name of that folder as the first argument of `update.packages`.
