### ISSUE TITLE
wrong result for the dclf statistic in dclf.test()?

### ISSUE THREAD

**Issue by marcelinodelacruz** [spatstat/spatstat#159]
Dear all:
I have found that  the dcfl statistic as computed by hand [following the equations in Baddeley et al. (2016): 394-395] does not coincide with the result provided by dclf.test(). See the example:

```r
set.seed(1)
cells.env<- envelope(cells, Lest, savefuns=T)
Sobs<- cells.env$obs
Sfuns<- cbind(Sobs, data.frame(attributes(cells.env)$simfuns)[,-1])
Stheo <- apply(Sfuns, 1,  mean,  na.rm=T)
T <- sum((Sobs-Stheo)^2)
T
# [1] 0.9546639
dclf.test(cells.env)$statistic$u
# [1] 0.0004719914

```

**Comment by baddstats** [comment]
Thanks for your question. There are a couple of explanations for the discrepancy:

- Equation (10.21) on page 394 of Baddeley Rubak and Turner (2015) defines the statistic T as the _integral_ of the squared difference. The code in your question computes the _sum_ of the function values at successive values of _r_. This sum should be multiplied by the step size (the difference between two successive values of _r_) to get the approximation to the integral. This explains the order-of-magnitude discrepancy.
- Some of the summary functions, including `Lest`, return a column containing the exact theoretical value `theo` which is the value expected for a completely random pattern. This is detected by `envelope` and is automatically used as the theoretical value unless `use.theory=FALSE` is specified in the call to `envelope`. The code in your question computes the theoretical values `Stheo` by taking the sample mean of the simulated values. That is, you used something like equation (10.22) loc.cit. This will give a slightly different result.

Several other options in `dclf.test` and `envelope` can affect the calculation but these do not affect this example.

**Comment by baddstats** [comment]
I've added more information to the help file for `dclf.test`.
