### ISSUE TITLE
some wrong distances in delaunayDistance() ??

### ISSUE THREAD

**Issue by marcelinodelacruz** [spatstat/spatstat#160]
Dear all,

When computing Delaunay distances with **delaunayDistance()**, it seems that  some distances are incorrectlly computed, mainly in the case of points on the convexhull of the pattern (or maybe the order of points in the Delaunay distance matrix is different from the order of points in the ppp). See the example for the second point in **ants** (`focal <- 2`).  It happens also for points 4, 7, 11, and 12 (maybe for others too).
 ```r
# Dirichlet tesselation
   ants.tes <- dirichlet(ants)
# Delaunay triangulation
   ants.tri <- delaunay(ants)
# Delaunay distances 
   ants.Deldis <- delaunayDistance(ants)

# Plot neighbours of  second point:
   focal <-2
   norder <- 1:ants$n
   # find neighbors based on Delaunay distance
   # and point order
   focal.neighbors <- norder[ants.Deldis[focal,] < 2]
   plot(ants[focal.neighbors])
   plot(ants.tes[focal.neighbors])
   points(ants[focal.neighbors])
   plot(ants.tri, lty=3, border="grey", add=T)
   # plot focal  point
   points(ants[focal], pch=19)
```
![image](https://user-images.githubusercontent.com/51702543/194400651-3e25b4b9-4ca2-4092-b2f2-c4d0f48b2768.png)

**Comment by baddstats** [comment]
Agreed. I will add a comment in the help file.
