### ISSUE TITLE
Install issue with spatstat.geom on R version 4.3.1

### ISSUE THREAD

**Issue by chuymtz** [spatstat/spatstat#162]
I believe there is an issue with spatstat.geom on R version 4.3.1. I could install all other dependencies except spatstat.geom. I could complain. When I reverted to 4.0.2 it worked just fine.

**Comment by rubak** [comment]
Could you please provide more details? Which operating system are you using and what is the exact error message? Can you please copy paste all the output that you see after executing `install.packages("spatstat.geom")`?

**Comment by rubak** [comment]
Closing now due to lack of response.
