### ISSUE TITLE
rLGCP depends on RandomFieldsUtils which is no longer supported

### ISSUE THREAD

**Issue by ClaudioHeinrich** [spatstat/spatstat#163]
The function `rLGCP` returns an error:

``` r
library(spatstat)
#> Loading required package: spatstat.data
#> Loading required package: spatstat.geom
#> spatstat.geom 3.2-2
#> Loading required package: spatstat.random
#> spatstat.random 3.1-5
#> Loading required package: spatstat.explore
#> Loading required package: nlme
#> spatstat.explore 3.2-1
#> Loading required package: spatstat.model
#> Loading required package: rpart
#> spatstat.model 3.2-4
#> Loading required package: spatstat.linnet
#> spatstat.linnet 3.1-1
#> 
#> spatstat 3.0-6 
#> For an introduction to spatstat, type 'beginner'
rLGCP()
#> Error: The package 'RandomFieldsUtils' is required
```

<sup>Created on 2023-07-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The package [`RandomFieldUtils`](https://cran.r-project.org/package=RandomFieldsUtils) was removed from CRAN in December 2022.
I also didn't manage to install it from CRAN archive or [github,](https://github.com/cran/RandomFieldsUtils). The compilation fails, and I am getting the warnings *this package has a configure script - It probably needs manual configuration* and *Warning in system(cmd) : 'make' not found*.

**Comment by baddstats** [comment]
You can install `RandomFields` and `RandomFieldsUtils` from [spatstat.r-universe.dev](spatstat.r-universe.dev).
We are hoping that these packages will be reinstated on CRAN sometime.

**Comment by baddstats** [comment]
This problem should not occur now. The dependence on `RandomFields` and `RandomFieldsUtils` has been removed in the latest versions of the `spatstat` packages available on CRAN.
