### ISSUE TITLE
Jest does not return Fest and Gest

### ISSUE THREAD

**Issue by ouroukhai** [spatstat/spatstat#164]
Hello spatstat team,

I noticed the following result:
```r
Jest(cells)$F
``` 
returns NULL

While the documentation mentions:
_The data frame also has attributes: F, G_
Is this something intentional?
Thank you for your time!
Sincerely

**Comment by ouroukhai** [comment]
It was an attribute found with attributes(Jest(cells))$F. That was my mistake. I am closing the issue.

**Comment by rubak** [comment]
It is because attributes of an R object (in this case a `fv` and `data.frame`) cannot be accessed by `$`. The correct function is `attr()`:

```r
library(spatstat)
Jcells <- Jest(cells)
attr(Jcells, "F")
```

**Comment by ouroukhai** [comment]
Thank you for the answer!
