### ISSUE TITLE
vignette('shapefiles') not found

### ISSUE THREAD

**Issue by edzer** [spatstat/spatstat#168]
I  loaded `spatstat` and typed `beginner`, then read the advice

```
To handle spatial data in the 'shapefile' format, see the document
"Handling shapefiles in the spatstat package", by typing
     vignette('shapefiles')
```
and tried
```r
     vignette('shapefiles')
```
but this gave
```
Warning message:
vignette ‘shapefiles’ not found 
```

**Comment by rubak** [comment]
Thanks for reporting. We removed the vignette in the last CRAN since it was based on `maptools` and `sp`. A new version using `sf` is on the way and will be submitted to CRAN within a month or so.

**Comment by edzer** [comment]
Thanks @rubak!
