### ISSUE TITLE
'ppp' is not an exported object from 'namespace:spatstat'

### ISSUE THREAD

**Issue by wangqi770319** [spatstat/spatstat#169]
Hello, I have the following problem!
The reference is Dr. Chai Zongzheng's doctoral thesis: Quantitative Evaluation of Forest Spatial Structure Based on Adjacent Wood Relations and implementation of R language programming.
Sample data and code are in Chapter 8
Enter the following code: 
 nnsp.N4 < -nnIndex (tree.pppX, id=tree.pppX$marks$tree.id, N=4, smark="sp.code", buffer=TRUE)
Prompt the following questions:Error: 'ppp' is not an exported object from 'namespace:spatstat'

**Comment by baddstats** [comment]
I do not have access to this doctoral thesis, or the code that you refer to.
The function `nnIndex` referred to in your question is presumably some code from the thesis.

The most likely explanation for your problem is that the code referred explicitly to the function `spatstat::ppp` which no longer exists. The `spatstat` package was split into 10 separate packages in 2020. The function `ppp` is now part of the sub-package `spatstat.geom`. So you could fix this by replacing `spatstat::ppp` by `spatstat.geom::ppp` or just `ppp` in the code you are trying to use.

**Comment by wangqi770319** [comment]
Thank you very much for your help! But I still want your help again,
I run the following code in the latest "RStudio" : 
install.packages("devtools")
install.packages("spatstat")
install_github("Zongzheng/forestSAS")
library(devtools)
library(spatstat)
library(forestSAS)
treedataX <- read.table("C:/Users/F/Documents/treedataX.txt", header=T, sep="\t")
treedataX
tree.pppX <- ppp(x = treedataX$x, y = treedataX$y,
window = owin(c(0, 30), c(0, 25)),
marks = treedataX[, c(1, 4:11)])
tree.pppX 
above code runs normally, no problem.
But the code that follows reports an error,
nnsp.N4 < -nnIndex (tree.pppX,id= tree.pppX$marks$tree.id, N=4,smark="sp.code",buffer=TRUE)
Error: 'ppp' is not an exported object from 'namespace:spatstat', 
how to solve it，Thank you for your help.

**Comment by wangqi770319** [comment]
If it is convenient, please provide some specific code operation steps, thank you very much!

**Comment by wangqi770319** [comment]
If it is convenient, please provide some specific code operation steps, thank you very much!

**Comment by wangqi770319** [comment]
If it is convenient, please provide some specific code operation steps, thank you very much

**Comment by baddstats** [comment]
`nnIndex` appears to be a function defined in the package `forestSAS` which you have installed by the line `install_github("Zongzheng/forestSAS")`. The problem lies in that package. I cannot help you. Please contact the author of that package.

**Comment by rubak** [comment]
@wangqi770319  I have forked the package and run an old script to substitute calls to spatstat with calls to relevant subpackages and made a pull request for the original author to include this in the package. Until the pull request is merged you should be able to install my fork by:
```
remotes::install_github("spatstat-revdep/forestSAS")
```
This fork will be absolutely unmaintained by me, so please contact the original package author about any further questions.
