### ISSUE TITLE
funxy() tampers with one-liners

### ISSUE THREAD

**Issue by WastlM** [spatstat/spatstat#18]
**spatstat** 1.45-0 made `funxy` more _and_ less general at the same time. The problem is that the new magic manipulation of the supplied function `f` assumes `body(f)` to be a call of "{". One-liners such as `f = function (x,y) sqrt(x^2+y^2)` yield wrong results (without a warning or error message)! It took me a while to trace back this problem when trying to reproduce an analysis originally conducted with spatstat 1.44-1. Here is a small example illustrating the erroneous behaviour:

```
fxy1 <- funxy(function (x, y) sqrt(x^2+y^2), letterR)
body(fxy1)[[length(body(fxy1))]]  # sqrt() is missing!!!

fxy2 <- funxy(function (x, y) {sqrt(x^2+y^2)}, letterR)
body(fxy2)[[length(body(fxy2))]]  # correct

par(mfrow=c(1,2)); plot(fxy1); plot(fxy2)
```

To correctly manipulate `f` in `funxy` one either needs to differentiate these two cases (as I do in `surveillance:::add.on.exit` defined [here](https://r-forge.r-project.org/scm/viewvc.php/pkg/R/plapply.R?view=markup&root=surveillance)) or, maybe simpler, to ensure first that `f` is a call of `{` and then proceed as in the current version of `funxy`. I came up with the following auxiliary function to do this pre-checking of `f`:

```
curlyf <- function (f)
{
    f <- match.fun(f)
    if (is.primitive(f)) { # body(f) is NULL
        stop("not implemented for primitive functions")
    }
    obody <- body(f)
    if (is.call(obody) && identical(as.name("{"), obody[[1L]])) {
        return(f)
    } else {
        ## body(f) is a symbol or a single call like sqrt(x^2 + y^2)
        body(f) <- as.call(c(as.name("{"), obody))
        return(f)
    }
}
```
I am not sure how to deal with primitive functions, but these are unlikely to be used in the `funxy` context.

**Comment by baddstats** [comment]
Thank you for drawing this bug to our attention. 
It has been fixed in the latest update (1.45-2.001)
