### ISSUE TITLE
DOCS: rescale doc issue

### ISSUE THREAD

**Issue by nickeubank** [spatstat/spatstat#22]
The docs for `rescale` say parameter `s` is "Conversion factor: the new units are s times the old units.". 

As noted below, however, "For example if X is a dataset giving coordinates in metres, then rescale(X,1000) will divide the coordinate values by 1000 to obtain coordinates in kilometres, and the unit name will be changed from "metres" to "1000 metres". Similarly rescale(X, 1000, "km") will divide the coordinate values by 1000 to obtain coordinates in kilometres, and the unit name will be changed to "km"."

So new units are old units *DIVIDED* by `s`, no?

**Comment by baddstats** [comment]
No. The new **unit of length** is `s` times the old unit of length. In the example above, the new unit of length, 1 kilometre, is 1000 times the old unit of length, 1 metre. 

The new **coordinate values** are obtained by dividing the old coordinate values by `s`. In the example above, 1500 metres becomes 1500/1000 = 1.5 kilometres.

**Comment by nickeubank** [comment]
Ahhh. Ok. Thanks for clarifying!

**Comment by baddstats** [comment]
Thanks for your feedback. The documentation has been improved in the latest version 1.46-1.021
