### ISSUE TITLE
Bug in plot.kppm when fitting method != "mincon"

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#23]
In this line:
https://github.com/spatstat/spatstat/blob/1e55b2ec6a28434d44b3426364bea269d66a431f/R/kppm.R#L1109
we get a logical(0) when the model isn't fitted via minimum contrast. Either we need to add a check for is.null or make another more robust way to check things here (e.g. a new function `clustertype` that extracts the cluster type from a kppm object).

**Comment by baddstats** [comment]
We could use `x$isPCP` or more robustly `summary(x, quick=TRUE)$isPCP` to check whether a kppm object is a cluster process. Or we could use `x$clusters` to extract the string name of the clustering model.

**Comment by baddstats** [comment]
oops.

I'll leave it to you to decide. 
Make a pull request?

**Comment by baddstats** [comment]
The `kppm` object contains `isPCP`, `clusters` and `modelname` which could all be relevant in different circumstances. I seem to recall someone from CRAN saying that this kind of thing should be extracted through the `summary` method, to minimise the number of additional functions. I will edit `summary.kppm` to do that, and you can decide whether you want a stand-alone function as well.

**Comment by baddstats** [comment]
Bug in `plot.kppm` has been fixed in `spatstat 1.46-1.028`

**Comment by rubak** [comment]
Great. Thanks for fixing it.
