### ISSUE TITLE
Spatial logistic regression failure

### ISSUE THREAD

**Issue by kcolyvas** [spatstat/spatstat#29]
The attached example is from a study to determine if there are any covariates that might explain the locations chosen by calling male frogs around the perimeter ponds. The sampling process involved finding calling frogs (presence) and recording covariate values for each frog. Then moving away from those locations using a random process and recording covariate values at those new locations. If any calling frogs were present in these new locations they were recorded too, but I think the expectation was many of these randomly chosen locations would represent the absences. 
So it seemed that a spatial logistic regression would be an appropriate analysis due to the comparison of covariate values between presence and absence sites

We (Ian Renner mainly and I) have tried to set up the attached code in accord with the example in the spatstat book but if fails at the modelling step with error message

Error in mpl.get.covariates(covariates, U, "quadrature points", covfunargs) : 
Each entry in the list 'covariates' should be an image, a function, a window, a tessellation or a single number

There are warnings when running the code about duplicate records but we did not think this would the reason for the failure of the model step.

[LR bug example .data.txt](https://github.com/spatstat/spatstat/files/605584/LR.bug.example.data.txt)
[LR bug example.R.txt](https://github.com/spatstat/spatstat/files/605585/LR.bug.example.R.txt)

> pres = ppp(x = presX, y = presY, window = pond.w)
Warning message:
In ppp(x = presX, y = presY, window = pond.w) :
  data contain duplicated points
> abs  = ppp(x = absX, y = absY, window = pond.w)
Warning message:
In ppp(x = absX, y = absY, window = pond.w) :
  data contain duplicated points

Any help would be appreciated,
Kim Colyvas
kim.colyvas@newcastle.edu.au

**Comment by baddstats** [comment]
...in accord with the example in the spatstat book..

Which example in the spatstat book are you referring to?
Currently `method="logi"` does not support a data frame of covariates. 
That is an oversight, and it would be desirable, so I will implement it soon.

**Comment by baddstats** [comment]
This has been fixed in `spatstat 1.47-0.034`
