### ISSUE TITLE
Spatial logistic regression - envelope failure

### ISSUE THREAD

**Issue by kcolyvas** [spatstat/spatstat#31]
After fitting a ppm model with method="logi" the code 
env.fit = envelope(fitlogi,fun=Kinhom)
failed with error message
Error in rmhmodel.ppm(Y, verbose = FALSE) : 
This model cannot be simulated, because the covariate values were given as a data frame.

Example code and data set attached.
[LR bug example .data.txt](https://github.com/spatstat/spatstat/files/658505/LR.bug.example.data.txt)
[LR bug example.data.txt](https://github.com/spatstat/spatstat/files/658510/LR.bug.example.data.txt)

Thanks,
Kim

**Comment by baddstats** [comment]
This is not a bug.
If the covariate values were given as a data frame (i.e. the values of the covariates are given at a finite set of sample points) then we don't know the covariate values at other locations throughout the spatial domain, so we can't simulate a point process which depends on the spatial covariates.
