### ISSUE TITLE
Issue 30 fix didn't work

### ISSUE THREAD

**Issue by kcolyvas** [spatstat/spatstat#32]
Issue 30 concerned the failure of the summary command on a fitted object using ppm with method="logi".
See response below from issue 30. After installing spatstat 1.47-0.053 the command still failed. 
Error in model.matrix.ppm(model) : 
internal error: model matrix does not match glm data frame

Example code and data set attached.
[LR bug example.R.txt](https://github.com/spatstat/spatstat/files/658619/LR.bug.example.R.txt)
[LR bug example.data.txt](https://github.com/spatstat/spatstat/files/658620/LR.bug.example.data.txt)

[However the workaround suggestion about NA values did work and we were able to move the next step and found a data frame related issue failure with the envelope command which is the subject of another issue submission. "This occurs when the data frame contains NA values. (The NA's are dropped in some circumstances and retained in others, leading to a mismatch in the dimensions of data frames.) An immediate workaround is to remove data that contains NA's. Either remove columns of the data frame that contain NA values (and of course remove these variables from the model formula), or remove rows of the data frame that contain NA's and remove the corresponding data points from the quadrature scheme. This bug has been fixed in spatstat 1.47-0.050."]

Regards,
Kim

**Comment by baddstats** [comment]
This should now be fixed (in `spatstat 1.47-0.055`)

**Comment by baddstats** [comment]
Fix is now included in the public release `spatstat 1.48-0`
