### ISSUE TITLE
Methods for function head()

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#33]
We could consider methods for `head()` for spatstat classes. At the moment `head.default` is dispatched for most classes and it doesn't do the right thing. E.g. `cells` is internally a list of length 5 so `head(cells, n)` with `n`>5 will incorrectly return a `ppp` containing the first 5 points of `cells`. A marked `ppp` has 6 elements so for e.g. Chorley it works as expected up to 6. Similarly with unmarked and marked `psp` objects you get at most either 4 or 5 segments in the result of `head`.

**Comment by baddstats** [comment]
OK. That seems reasonable for list-like objects such as `ppp`, `psp`, `lpp`, `solist`, ..
 But if X is an `owin`, what should `head(X)` return?

**Comment by baddstats** [comment]
In the book we suggest using `head(as.data.frame(X))` to get the first few entries of `X` where `X` could be a point pattern, etc. Do we want `head(X)` to be equivalent, or something different?

**Comment by baddstats** [comment]
I suggest that the result of `head(X)` should have the same class as `X` where possible. So `head.ppp` would be like `head.default` except that it would use `npoints` to determine the appropriate number of points to extract.

**Comment by rubak** [comment]
I think we should ignore`owin`. If you use `head` on an `owin` you get an error as you deserve :-)

A `solist` is already handled correctly by `head.default`. To handle `ppp`, `lpp` and `psp` we could even mask `head.default` with the following function:
```
head.default <- function (x, n = 6L, ...){
    stopifnot(length(n) == 1L)
    spst <- inherits(x, c("ppp", "lpp", "psp")
    length_x <- if(spst) nrow(coords(x)) else length(x)
    n <- if (n < 0L) 
        max(length_x + n, 0L)
    else min(n, length_x)
    x[seq_len(n)]
}
```

**Comment by baddstats** [comment]
Done (in `spatstat 1.47-0.055`) using `nobjects`
