### ISSUE TITLE
documentation update: ppp/check should also be turned off to suppress duplicate point warnings

### ISSUE THREAD

**Issue by MichaelChirico** [spatstat/spatstat#34]
Hey,

I have been using `ppp` on some data that I know contains duplicated coordinates. I'm fine with this, and was looking to see if `ppp` has an argument to ignore warning me about this.

A read of `?ppp` suggests that it's _not_ the case, so I was resigned to using `suppressWarnings`, but I checked the code of `ppp` and I see:

        if (check && anyDuplicated(pp)) 
            warning("data contain duplicated points")

Thus it seems the `check` argument has a second undocumented use to suppress this warning. So I guess it should be added to the manual page.

Thanks!

**Comment by baddstats** [comment]
New argument `checkdup` will be added to `ppp` shortly
