### ISSUE TITLE
Multiple marks in lpp

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#36]
In `lpp` a `data.frame` of marks is saved as a `hyperframe` in the internal `ppx` format. In `plot.lpp` we call `as.ppp` which generates an error since `ppp` doesn't allow a `hyperframe` of marks:

```
library(spatstat)
X <- chicago
marks(X) <- data.frame(m1 = marks(chicago), m2 = 0)
plot(X)
``` 
```
Error in `marks<-.ppp`(`*tmp*`, value = marks(X)) : 
  Hyperframes of marks are not supported in ppp objects; use ppx
```

**Comment by baddstats** [comment]
This is about to have been fixed (in `spatstat 1.48-0.011`)
