### ISSUE TITLE
is pixellate/ppp _guaranteed_ to return sorted coordinates?

### ISSUE THREAD

**Issue by MichaelChirico** [spatstat/spatstat#37]
I'm running a routine basically equivalent to:

```
library(spatstat)
DF = as.data.frame(pixellate(humberside))
```

It would be very helpful if I could be assured that `x` and `y` in the result are sorted, but I don't see this anywhere in the documentation (`?as.data.frame.im`, `?pixellate.ppp`, `?ppp` and `?ppp.object` are all quiet on this point).

But it appears to be true empirically... basically, I want to know if this always holds true for `data.frame`s resulting from `im`/`ppp` objects:

    identical(DF, DF[order(DF$x, DF$y), ])

**Comment by baddstats** [comment]
Yes, `as.data.frame.im` always returns a data frame in which the entries are sorted in increasing order of the `x` coordinate, and increasing `y` within `x`.

This has nothing to do with `pixellate` or `ppp`.

**Comment by MichaelChirico** [comment]
shouldn't this be added to `?as.data.frame.im`?
