### ISSUE TITLE
Make as.solist work for single object?

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#40]
At the moment the following fails:
```r
library(spatstat)
as.solist(cells)
```
The problem is in [line 104 of solist.R](https://github.com/spatstat/spatstat/blob/c10ef9c630f64905292d117bea47dbe77bfcae7a/R/solist.R#L104).
However, in some functions it can be convenient to ask the user to supply either a single spatial object or a list of spatial objects and then make sure it is a `solist` (with either one or several components) before proceeding.  I suggest to replace line 104 by
```r
  if(!is.list(x) | is.sob(x))
```
which makes it work, and doesn't have any negative consequences that I can spot.

**Comment by baddstats** [comment]
Done!
