### ISSUE TITLE
Feature Request: as.GridTopology.ppp

### ISSUE THREAD

**Issue by MichaelChirico** [spatstat/spatstat#42]
Hi, I've got a problem where I'd like to convert a `ppp` object to a `GridTopology` object in order to facilitate using `splancs::spkernel2d`.

Unfortunately I'm relying on sort of ad-hoc methods of creating equivalent `ppp` and `GridTopology` objects; it would be nice to have a formal method for converting between the two.

**Comment by rubak** [comment]
This seems strange to me. I'm not familiar with a `GridTopology` object, but surely it must be related to grid data, so it seems more natural to convert to/from `im` objects in `spatstat`. To convert between `sp` and `spatstat` grid formats simply use `as.SpatialGridDataFrame.im` from `maptools`:
```r
library(spatstat)
library(maptools)
x <- density(unmark(chorley))
y <- as.SpatialGridDataFrame.im(x)
```
I think from there you can play with `GridTopology` using `sp`. E.g:
```r
z <- as(y, "GridTopology")
```
If that is meaningful in any way to you (it isn't to me)?
If your end goal is to do some kernel smoothing you could just use `Smooth` (note upper case S) in `spatstat`...

**Comment by MichaelChirico** [comment]
yes! sorry, I was mistaken -- I actually am converting from im to
GridTopology.

Thanks!

On Jan 27, 2017 1:23 AM, "Ege Rubak" <notifications@github.com> wrote:

This seems strange to me. I'm not familiar with a GridTopology object, but
surely it must be related to grid data, so it seems more natural to convert
to/from im objects in spatstat. To convert between sp and spatstat grid
formats simply use as.SpatialGridDataFrame.im from maptools:

library(spatstat)
library(maptools)x <- density(unmark(chorley))y <- as.SpatialGridDataFrame.im(x)

I think from there you can play with GridTopology using sp. E.g:

z <- as(y, "GridTopology")

If that is meaningful in any way to you (it isn't to me)?
If your end goal is to do some kernel smoothing you could just use Smooth
(note upper case S) in spatstat...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spatstat/spatstat/issues/42#issuecomment-275597583>,
or mute
the thread
