### ISSUE TITLE
FR: offer control over type of output in empty pixellate.ppp?

### ISSUE THREAD

**Issue by MichaelChirico** [spatstat/spatstat#45]
This is closely related to what I'm trying to accomplish in #44.

In [this](https://github.com/spatstat/spatstat/blob/master/R/pixellate.R#L58) line, `pixellate.ppp` forces its output type when presented an empty `ppp` to be `numeric`:

```
sapply(as.data.frame(pixellate(ppp(xrange = 0:1, yrange = 0:1))), class)
#         x         y     value 
# "numeric" "numeric" "numeric"
```

However, I need to combine the resultant `data.frame` (actually, `data.table`) with some `ppp` that have `value` as `integer`:

```
sapply(as.data.frame(pixellate(ppp(x = .5, y = .5, yrange = 0:1, xrange = 0:1))), class)
#         x         y     value 
# "numeric" "numeric" "integer" 
```

Specifically, the following operation fails:
```
library(data.table)
DT = data.table(x = c(NA, .5), y = c(NA, .5), ID = c(1, 2))
DT[ , as.data.table(pixellate(
  if (all(is.na(x)))
    ppp(xrange = 0:1, yrange = 0:1)
  else 
    ppp(x = x, y = y, xrange = 0:1, yrange = 0:1),
  eps = c(1/3, 1/3))), by = ID]
```
> Error in `[.data.table`(DT, , as.data.table(pixellate(if (all(is.na(x))) ppp(xrange = 0:1,  : 
  Column 3 of result for group 2 is type 'integer' but expecting type 'double'. Column types must be consistent for each group.

Either of two solutions that `spatstat` could implement would be greatly appreciated:

 - Offer a user-facing option to control what type `pixellate.ppp` casts for `value` when faced with an empty `ppp`
 - Change the default in the aforementioned line to `as.im(0L, W)` (this seems more natural to me anyway -- though I don't know the full gamut of use cases for `pixellate`ing empty `ppp`s, so maybe I'm missing something)

**Comment by rubak** [comment]
I think it should just always return `integer`. I will talk to Adrian about fixing this ASAP.

**Comment by baddstats** [comment]
I think the result for an empty point pattern should be `integer` if `weights=NULL`.

If `weights` is a zero-length numeric vector, etc, then the result should be `numeric`. 

I'll fix this.

**Comment by MichaelChirico** [comment]
if it's as simple as changing the referenced line, I'm happy to code up a
PR. let me know
