### ISSUE TITLE
win/window parameter name inconsistency

### ISSUE THREAD

**Issue by barryrowlingson** [spatstat/spatstat#47]
Some spatstat functions use `win` and some use `window`. Spatstat's defaults mean mistyping does not cause an error, but can generate a wrong window. And R's floppy parameter matching mean users often abbreviate parameter names and expect the right thing to happen.

Here x and y are some points in a disc(10):

`ppp` uses `window`:

```
> p = ppp(x,y, window=disc(10))
>
```

and using `win` fails (here with a warning, but possibly silently):
```
> p = ppp(x,y, win=disc(10))
Warning message:
299 points were rejected as lying outside the specified window 
```
because it uses a default (0,1) box window.

Conversely `rpoispp` uses `win`:

```
> p = rpoispp(10, win=disc(10))
> p
Planar point pattern: 3149 points
window: polygonal boundary
enclosing rectangle: [-10, 10] x [-10, 10] units
```
And using `window` fails silently by generating a pattern in a default 0,1 box:
```
> p = rpoispp(10, window=disc(10))
> p
Planar point pattern: 8 points
window: rectangle = [0, 1] x [0, 1] units
```

Could this inconsistency be patched up?

**Comment by barryrowlingson** [comment]
And in some places the window argument is a single capital W:
```
> args(rStrauss)
function (beta, gamma = 1, R = 0, W = owin(),
```

**Comment by rubak** [comment]
This is definitely something that could be nice to clean up, and we have discussed it internally before. I can no longer remember the complications, but I think it will be somewhat difficult to clean up. Especially keeping backwards compatibility is tricky. Thanks for reminding us. We will keep it open for now until we know for sure what can and cannot be done.

**Comment by baddstats** [comment]
This is a known problem. It arose because it is sometimes necessary to pass two window objects in a function call - one window to be used by the main function, and the other destined to be passed through the `...` arguments to a call to another function. 

It's difficult to fix this now without breaking backward compatibility.
