### ISSUE TITLE
Add argument to solist and as.solist?

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#49]
In simulation algorithms we typically make a list of `ppp`s and then assign names `paste("Simulation", 1:n)` and then call `as.solist`. Sometimes (`runifpoispp(1, drop = FALSE)`) the names are forgotten so they end up being `"Component 1"` etc. Given many return points in simulation code could it be convenient to have an argument to control the names in `solist` and `as.solist`? E.g.
```r
as.solist(mylist, .NameTemplate = "Simulation")
solist(myobj1, myobj2, .NameTemplate = "My name")
```

**Comment by baddstats** [comment]
Done.
