### ISSUE TITLE
no method or default for coercing “SpatialPolygons” to “owin”

### ISSUE THREAD

**Issue by eotp** [spatstat/spatstat#54]
Hi,
I tried to reprodcue the example in the [vignette](https://cran.r-project.org/web/packages/spatstat/vignettes/shapefiles.pdf) in order to convert an object of type  `SpatialPolygons` to a single object of class `owin`. 

```
X <- readOGR(...)
class(X)
[1] "SpatialPolygonsDataFrame"
attr(,"package")
[1] "sp"

X <- as(X, "SpatialPolygons")
class(X)
[1] "SpatialPolygons"
attr(,"package")
[1] "sp"

as(X, "owin")
 Show Traceback
Error in as(X, "owin") : no method or default for coercing “SpatialPolygons” to “owin”
```

What am I doing wrong? 
Thanks.

**Comment by rubak** [comment]
I believe that the method to coerce `SpatialPolygons` to `owin` is in `maptools`. Did you remember to do `library(maptools)` first?

**Comment by eotp** [comment]
good catch!
yeah, I didn´t add `maptools` beforehand.
Thanks.
