### ISSUE TITLE
Smooth.ppp crashes if marks are NA

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#55]
Maybe we should handle this example

    df <- data.frame(x=runif(3), y=runif(3), m = c(1, 2, NA))
    X <- as.ppp(df, W=owin())
    Smooth(X)

more gracefully than this:

    Error in (function (x, values, sigma, ..., weights = NULL, varcov = NULL,  : 
      NA/NaN/Inf in foreign function call (arg 4)
    In addition: Warning messages:
    1: some mark values are NA in the point pattern X 
    2: some mark values are NA in the point pattern X 
    3: some mark values are NA in the point pattern X

**Comment by baddstats** [comment]
Fixed!
