### ISSUE TITLE
user supplied pixel grid for density.ppp

### ISSUE THREAD

**Issue by dschuhmacher** [spatstat/spatstat#56]
I have noticed some unexpected behaviour in density.ppp. I use the humberside data for illustration. I am aware that it does not make much sense to choose sigma so small for this data set, but for my own data it does make sense and the issue remains. 

If I say
```
xi <- unmark(humberside)
d <- density(xi, sigma=1)
plot(d)
```
everything runs as expected. However, if I supply my own pixel grid to compute the density via
```
xcoor <- seq(4690, 5415, 5)
ycoor <- seq(4150, 4760, 5)
d2 <- density(xi, sigma=1, xy=list(x=xcoor, y=ycoor))
plot(d2)

```
we see a lot of mass getting concentrated in one single pixel. I could understand this (to some extent) if the intersection of the pixel with the observation window were tiny, but from plotting the boundary with `plot(xi$window,add=TRUE)` it seems that it is not. The issue seems to disappear if we make sigma somewhat larger, but becomes much more pronounced if we make it smaller.

Since sigma is small I could live in fact with not doing an edge correction. However, if I say
```
d3 <- density(xi, sigma=1, xy=list(x=xcoor,y=ycoor), edge=FALSE)
plot(d3)

```
the visual impression looks fine, but the scaling becomes wrong (set sigma=0.1 and observe how the density values increase by a factor of 10).

**Comment by baddstats** [comment]
Thank you for spotting this.

I have fixed two bugs relating to this behaviour. 
Please check that the examples above work satisfactorily now (in spatstat 1.51-0.063)

Numerical artifacts still occur if sigma is less than 1/7 the pixel width (which is true in your example if sigma <= 0.7). I will probably have to trap such cases explicitly and just return the pixellated pattern. I won't do that just yet.

**Comment by dschuhmacher** [comment]
Thank you for fixing this.

Indeed it works fine now both with the above and with my original example.

Just pixellating the point pattern if sigma is less than 1/7 the pixel width seems fine to me. I actually misinterpreted what happens when sigma is small, and assumed the error committed by just pixellating was larger. Now I see that it is really tiny in my example and should be tiny in general.
