### ISSUE TITLE
kernel names in density function don't match with function 

### ISSUE THREAD

**Issue by carbonmetrics** [spatstat/spatstat#57]
kernel names in density function help:
`        kernel = c("gaussian", "epanechnikov", "rectangular",
                   "triangular", "biweight",
                   "cosine", "optcosine")`

```density(redwood, bw.ppl, kernel = "biweight")
Error: Unrecognised choice of kernel ‘biweight’ (options are ‘gaussian’, ‘epanechnikov’, ‘quartic’ and ‘disc’)
density(redwood, bw.ppl, kernel = "biweight") # works
```

**Comment by rubak** [comment]
The help page for the generic function `density` (and its default method `density.default`) concerns univariate kernel density estimation in base R while `density.ppp` is the function used to estimate the intensity for point patterns. These functions have different arguments and `kernel = "biweight"` is not supposed to work for point patterns. Are you saying that `density(redwood, bw.ppl, kernel = "biweight")` in fact works? That would be very surprising and it is not the case on my machine.

**Comment by carbonmetrics** [comment]
No, biweight doesn't work, quartic does - I have edited the question.

**Comment by rubak** [comment]
Yes, this is as described in the help `?density.ppp`:

    kernel: The smoothing kernel.  A character string specifying the
            smoothing kernel (current options are ‘"gaussian"’,
            ‘"epanechnikov"’, ‘"quartic"’ or ‘"disc"’), or a pixel image
            (object of class ‘"im"’) containing values of the kernel, or
            a ‘function(x,y)’ which yields values of the kernel.

So unless you have some other problem I will consider this solved and close the issue?

**Comment by carbonmetrics** [comment]
Yes, issue can be closed. I should have put `?density.ppp` instead of `?density` for the `density command`.
