### ISSUE TITLE
Error in mpl.prepare(.........

### ISSUE THREAD

**Issue by elgabbas** [spatstat/spatstat#6]
Hi all,
I am receiving this error message:
"Error in mpl.prepare(Q, X, P, trend, interaction, covariates, want.trend,  : 
  interaction evaluator did not return a matrix"

When trying to run an area-interaction model using this code:
plike <- profilepl(rs, AreaInter, Q, trend=int.form, covariates=int.list)

[I am following the code mentioned in the supplementary materials of the under-publication of Renner et al. about point process models and presence-only SDM - The same chunks of code worked before few weeks ago but with repeating the same code again I receive the error stated above]

Any help is appreciated,
Thanks,
Ahmed

**Comment by rubak** [comment]
Hi Ahmed,
Could you please provide a short reproducible example showing when this happens? (Using as few lines of code as possible from the reference you mention.)
Cheers,
Ege

**Comment by elgabbas** [comment]
Hello Ege,
It seems that the problem comes with the updates done on the package in the recent few months.
I am working on the most recent version of R and SpatStat v1.40-0 and the same error message appears while processing the same code on two different PCs. I tried out to remove this version and install an experimental version through out github and the same error message appears.

However, I tried an older version of SpatStat from the CRAN archive (http://cran.r-project.org/src/contrib/Archive/spatstat/  -- Version 1.37-0) and it works fine without any errors. So I think it should be a bug happened while updating the package in one of the more recent versions than v 1.37-0.

I am not sure if I can copy/paste some codes from a publication that has not been published yet due to copyright issues. I will ask one of the authors if I can do so before pasting the code here. 

PS: Dr. Adrian Baddeley (the main author of Spatstat) is also one of the co-authors of the publication mentioned above, so he should be familiar with such line of code

Thanks a lot,
Ahmed

**Comment by rubak** [comment]
OK. Thank you for the thorough answer. If you succeed in making an example of where it fails (maybe just inspired by the code without actually copying it) or get permission to send some code to me then please let me know. I didn't realise that Adrian was co-author, so I will ask him if he knows where this comes from when I talk to him next week. He is very busy right now, so I don't expect an answer right away.

**Comment by baddstats** [comment]
This is a bug. Thank you for bringing it to our attention. It will be fixed shortly (in spatstat version number 1.40-0.017)

**Comment by baddstats** [comment]
Bug is now fixed.
