### ISSUE TITLE
Bug in plot.lpp for patterns with multiple marks

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#60]
```
library(spatstat)
X <- runiflpp(2, simplenet)
marks(X) <- cbind(m1 = 1:2, m2 = 3:4)
plot(X
```
This gives an error since `plot.lpp` expects that marks are a `data.frame` but in fact they are a `hyperframe` in this case. The (first) problematic line is here:
https://github.com/spatstat/spatstat/blob/master/R/lpp.R#L110

Two obvious fix strategies:
1. Allow this to be a `hyperframe` (but these can be hard to plot in general).
2. Coerce to `data.frame` and warn about requested columns left out due to this.

This caused problems in [this question on SO](https://stackoverflow.com/q/45549959/3341769).

**Comment by baddstats** [comment]
I will implement (2)

**Comment by baddstats** [comment]
Fixed.
