### ISSUE TITLE
LinearK failing on disconnected network

### ISSUE THREAD

**Issue by rubak** [spatstat/spatstat#61]
Problem located while answering [this question on SO](https://stackoverflow.com/q/45912178/3341769) and I suspect the problem is that a component has no points.

``` r
library(spatstat)
#> Loading required package: nlme
#> Loading required package: rpart
#> 
#> spatstat 1.52-1.005       (nickname: 'Frame Dragging') 
#> For an introduction to spatstat, type 'beginner'
l <- thinNetwork(simplenet, retainedges = c(-3,-10))
#> Warning: Network is not connected
set.seed(42)
X <- runiflpp(2, l)
plot(X)
```

![](http://i.imgur.com/jDFHOpj.png)

``` r
linearK(X)
#> Error in retainedges[dat$seg]: invalid subscript type 'list'
```

**Comment by baddstats** [comment]
Bug was in `thinNetwork` so it affected all the second-order functions for linear networks.

Fixed in `spatstat 1.52-1.006`
