### ISSUE TITLE
Export units and print.units etc as S3 class/methods?

### ISSUE THREAD

**Issue by andybega** [spatstat/spatstat#63]
`spatstat` has a conflict with [r-quantities/units](https://github.com/r-quantities/units) that also affects [r-spatial/sf](https://github.com/r-spatial/sf) and other packages that use `units`. 

The issue is that `spatstat::print.units()` conflicts with the `units:::print.units()` method. The latter is exported as a S3 method for a "units" class. Example:

```
library("units")

# works
set_units(1000, "m")
print(set_units(1000, "m"))

library("spatstat")

# error
set_units(1000, "m")
print(set_units(1000, "m"))

# but this works
units:::print.units(set_units(1000, "m"))
```

Changing the order in which the packages are loaded does not fix the error, possibly because `spatstat`'s [foo].units functions are not exported as S3 methods (see r-spatial/sf#523). And there is no warning about the conflict when the packages are loaded, only for `spatstat::as.units`:

```
> library("units")
> library("spatstat")
Loading required package: spatstat.data
Loading required package: nlme
Loading required package: rpart

spatstat 1.53-2       (nickname: ‘Quantum Entanglement’) 
For an introduction to spatstat, type ‘beginner’ 


Attaching package: ‘spatstat’

The following object is masked from ‘package:units’:

    as.units

```

Same issue at r-quantities/units#66.

**Comment by baddstats** [comment]
The NAMESPACE file already contains `S3method` declarations for `print.units` and other methods for the class `units` defined in `spatstat`. That is, these methods are already exported as S3 methods.

I think your problem is that the methods are also exported by `export` declarations so that they can mask other functions with the same name. Presumably you want me to delete the `export` declarations and retain the `S3method` declarations so that these methods are no longer visible but are available for method dispatch.

I will have to check whether this is feasible without breaking any of the dependencies of `spatstat`.
To be advised ....

Incidentally, the NAMESPACE file is automatically generated, so I can't accept pull requests for changes to this file.

**Comment by andybega** [comment]
Thanks for clarifying, I think that's right.

**Comment by baddstats** [comment]
In `spatstat 1.53-2.012` the class `units` has been renamed `unitname`. Consequently `as.units` is now called `as.unitname` and should not generate a collision, at least with the `units` package. The methods for class `units` have been renamed accordingly. 

This Issue will remain open for a while in case any problems emerge - please report them here.

**Comment by edzer** [comment]
I'm glad to hear that -- thanks a lot!

**Comment by edzer** [comment]
With spatstat 1.55-0, I'm still running into a units collision; test file `sf/tests/zzz.R' gives stacktrace:
```
> traceback()
19: stop("both operands of the expression should be \"units\" objects")
18: Ops.units(mul, 0)
17: makeunitname(s[[1]], s[[2]], s[[3]])
16: as.unitname(x$units)
15: unitname.owin(w)
14: unitname(w)
13: as.unitname(unitname)
12: owin(w$xrange, w$yrange, unitname = unitname(w))
11: as.rectangle(x)
10: spatstat::edges(x)
9: as.matrix(spatstat::edges(x)$ends)
8: st_as_sf.psp(spatstat::as.psp(spatstat::domain(x)))
7: st_as_sf(spatstat::as.psp(spatstat::domain(x)))
6: st_as_sf.lpp(chicago)
5: st_as_sf(chicago) at zzz.R#5
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("sf/tests/zzz.R", , T)
```
I traced it down to `makeunitname`, which has lines
```r
    if (length(mul) != 1 || mul <= 0) 
        stop("In unit name, third entry should be a single positive number")
```
where, when debuggin, mul is
```r
Browse[2]> str(mul)
Class 'units'  num 1
```
but the `<=` operator is picked from package units, and that breaks (it wants to have units objects on both sides of the operator, so it can e.g. compare mm to m). I could easily create a PR that does `as.numeric(mul) <= 0`, but the true problem seems deeper: spatstat still creates `units` objects.

**Comment by rubak** [comment]
I can't recreate this. Do you have a newer version of `zzz.R` than what's on GitHub? The following runs without any issues for me with `spatstat_1.55-0` and `sf_0.6-0`:

```{r}
source("https://raw.githubusercontent.com/r-spatial/sf/master/tests/zzz.R", , T)
```

Any guess at what's going on?

**Comment by baddstats** [comment]
This is happening because some of the **installed** datasets like `chicago` still have the old structure in which the unit information has class `units` rather than `unitname`. 

I will re-build these datasets under the new format and update the package `spatstat.data` on CRAN.

I'll also update the code for `makeunitname` so that `mul` is converted to numeric.

**Comment by edzer** [comment]
@rubak understandable, this was triggered by the dev (github) version of `units`.

@baddstats thanks for this!

**Comment by edzer** [comment]
I ran into a stale spatstat "units" object in lansing:
```r
library(spatialEco)
x  <- spatstat::unmark(split(lansing)$maple)
o.ring(x)
# Error in Ops.units(sing, "unit") : 
#   both operands of the expression should be "units" objects
```
which will now cause `spatialEco` to fail on CRAN with `sf` to be submitted to CRAN - @jeffreyevans

@baddstats when may we expect an updated version of `spatstat.data` on CRAN?

<details>

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spatialEco_1.1-0    spatstat_1.55-1     rpart_4.1-13       
[4] nlme_3.1-137        spatstat.data_1.2-0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17         lattice_0.20-35      deldir_0.1-15       
 [4] class_7.3-14         sf_0.6-4             grid_3.5.0          
 [7] spData_0.2.8.3       DBI_1.0.0            magrittr_1.5        
[10] units_0.6-1          e1071_1.6-8          tensor_1.5          
[13] goftest_1.1-1        Matrix_1.2-14        spatstat.utils_1.8-0
[16] tools_3.5.0          polyclip_1.8-7       abind_1.4-5         
[19] compiler_3.5.0       classInt_0.2-3       mgcv_1.8-23         

</details>

**Comment by baddstats** [comment]
An update will be uploaded today.

**Comment by edzer** [comment]
Thanks a lot - this solved the issue!
