### ISSUE TITLE
parallel envelope() ?

### ISSUE THREAD

**Issue by elgabbas** [spatstat/spatstat#7]
Hello all,

I am somehow newbie to the Spatstat package. I wonder if there is a way to improve the speed of running ppm model diagnostics using the envelope() function. For just 250 simulations of one of my models, it is expected to be finished in 9 hours! 
My question is: is there a way to make it somehow faster using the multicore advantage of my processor? I am running a windows server virtual machine with 24 cores, is it possible to make such simulations in a parallel way (e.g. using foreach() or equivalent way) and then to collect the whole simulations once finished and having one envelope plot?

Thanks,
Ahmed

**Comment by rubak** [comment]
Hello Ahmed,

At the moment we do not directly support parallel computations in `spatstat`, but leave it to the user to do this manually. The solution would be to use one of `foreach`, `parLapply`, ... to generate simulations from the fitted model in parallel using `simulate.ppm(fit)` on each core, where `fit` is your `ppm` object. If all the 250 simulations then are collected in a list `sim` you can call `envelope.ppm` with the argument `simulate` like this (where the rank `N` is chosen according to the desired significance level of the hypothesis test):

```{r}
e <- envelope(fit, nsim = 250, nrank = N, simulate = sim)
```

I hope that helps,
Ege

**Comment by elgabbas** [comment]
I think, so far, most of time is consumed while running of the simulations.
I will try your solution.
Thanks a lot.
Ahmed
