### ISSUE TITLE
pseudoR2 function on models with offset

### ISSUE THREAD

**Issue by jenast** [spatstat/spatstat#70]
As far as I can tell, the pseudoR2.ppm function compares the model in question with a null model that includes only the intercept (in pseudoR2.ppm : nullmod <- update(object, . ~ 1, forcefit = TRUE)). 

However, for models with an offset, it seems appropriate to keep this offset also in the null model.  When I tried this manually, it made quite the difference.

If this sounds reasonable, I suggest that the default behaviour of the pseudoR2.ppm function is to keep the offset term, if present in the model$call. This is perhaps not general enough, but something in the lines of:

if(any(grepl("offset\\(", object$call)){
      nullFormula <- as.formula(paste(". ~ 1 +", gsub("(.*)(offset)", "\\2", object$call)[2]))
    } else 
      nullFormula <- as.formula(paste(". ~ 1"))
 nullmod <- update(object, nullFormula, forcefit = TRUE, ...)

 Cheers,

Jens

**Comment by baddstats** [comment]
This has now been implemented. Thank you for the suggestion.

**Comment by jenast** [comment]
That was fast. Thanks!
