### ISSUE TITLE
as.owin requires maptools to convert SpatialPolygons, but does not report this

### ISSUE THREAD

**Issue by DOSull** [spatstat/spatstat#71]
When you call `as.owin(x)` where x is a SpatialPolygons object, the reported error is

    Error in as.owin.default(Z, ..., fatal = fatal) : 
      Can't interpret W as a window

A bit of searching around shows that the problem is that maptools is required to be loaded, see e.g. issue #54. It would be more helpful, surely to have the error message report that this is the problem, or even to require maptools so that if a user has it installed then the error does not occur?

**Comment by baddstats** [comment]
Yes, we can improve the error message. Thank you for the suggestion.

We are not going to make `spatstat` depend on `maptools` for several reasons including the difficulty of installation and the licence restrictions - `spatstat` and all its dependencies are Free Open Source, and do not have any additional system requirements, and we want to keep it that way.

**Comment by DOSull** [comment]
Thanks for response - clearer error message would be perfect.
