### ISSUE TITLE
trivial cases of nncross.ppp() may have inconsistent return type

### ISSUE THREAD

**Issue by WastlM** [spatstat/spatstat#74]
`nncross.ppp()` is documented to return a vector if `k=1` and only one of "dist" or "which" is requested via the argument `what`. However, in the trivial case where `npoints(X) == 0`, `nncross.ppp()` will always return a data frame. See the code here:

https://github.com/spatstat/spatstat/blob/fe10bda0ee3033516fb6e84f2a6f868be62ca628/R/nncross.R#L54-L56

For example:

```r
data(cells)
str(nncross.ppp(cells, edges(cells), what = "dist"))
```
```
num [1:42] 0.025 0.087 0.05 0.025 0.125 0.087 0.15 0.162 0.212 0.237 ...
```
but:
```r
str(nncross.ppp(cells[0,], edges(cells), what = "dist"))
```
```
'data.frame':	0 obs. of  1 variable:
 $ dist: num 
```
For consistency, the result should be `numeric(0L)` in this trivial case.

**Comment by baddstats** [comment]
Thanks for spotting this. It is now fixed.
