### ISSUE TITLE
Comparing the results of `density.ppp` for `kernel = “gaussian”` and Gaussian kernel rebuild by user

### ISSUE THREAD

**Issue by SummerHaste** [spatstat/spatstat#77]
For my project, I called `density.ppp` with `kernel = "gaussian"` and compared its outcome with the results from calling `density.ppp` with my own kernel function which reproduces a Gaussian kernel.

I found that for the Gaussian kernel this behaves much differently from doing the same thing for other built-in kernels, e.g. `kernel = "quartic"`.

I understand that this is because the kernel values are calculated differently conditional on the kernel that is used. For all kernels but the `"gaussian"`-one `evaluate2Dkernel` is called. The kernel value computations for `kernel = "gaussian"` on the other hand are hard-coded into `densitypointsEngine` and `second.moment.engine`.

I had two main issues with this:  

 1. If one uses `at = "points"` and `leaveoneout = FALSE`,

        # ----- contribution from point itself ----------------
        if(!leaveoneout) {
        # add contribution from point itself
        self <- const
        if(!is.null(weights))
          self <- self * weights
        result <- result + self
      }

 is executed.

 Prior to that, `const` is set. For all kernels but the
    `"gaussian"`-one, we have `const <- 1/sigma^2 `. For `kernel = "gaussian"`, `const` is
    afterwards set to `const <- const/(2*pi)` in order to use it as the
    constant before the exponntial function in the hard-coded kernel
    value computation:

        # constant factor in density computations
        if(is.null(varcov)) {
          const <- 1/sigma^2 
        } else {
          detSigma <- det(varcov)
          Sinv <- solve(varcov)
          const <- 1/sqrt(detSigma)
        }
        if(isgauss) {
          # absorb leading constant in Gaussian density
          const <- const/(2 * pi)
        }

I think this is incorrect, because it should always add `1/sigma^2` for the point that is not left out, but if `kernel = "gaussian"` it adds `1/2*pi*(sigma^2)`. Am I right about this?

 2. Somehow, I temporarily was convinced that my results for `kernel = "gaussian"` vs. my Gaussian-kernel-rebuild also differed because in `second.moment.engine` one finds

        # set up kernel
        xcol.ker <- xstep * c(0:(nc-1),-(nc:1))
        yrow.ker <- ystep * c(0:(nr-1),-(nr:1))
        kerpixarea <- xstep * ystep
        if(identical(kernel, "gaussian")) {
          if(!is.null(sigma)) {
            densX.ker <- dnorm(xcol.ker, sd=sigma)
            densY.ker <- dnorm(yrow.ker, sd=sigma)
            #' WAS:  Kern <- outer(densY.ker, densX.ker, "*") * kerpixarea
            Kern <- outer(densY.ker, densX.ker, "*")
            Kern <- Kern/sum(Kern)
          } else if(!is.null(varcov)) {
            ## anisotropic kernel
            detSigma <- det(varcov)
            Sinv <- solve(varcov)
            halfSinv <- Sinv/2
            constker <- kerpixarea/(2 * pi * sqrt(detSigma))
            xsq <- matrix((xcol.ker^2)[col(Ypad)], ncol=2*nc, nrow=2*nr)
            ysq <- matrix((yrow.ker^2)[row(Ypad)], ncol=2*nc, nrow=2*nr)
            xy <- outer(yrow.ker, xcol.ker, "*")
            Kern <- constker * exp(-(xsq * halfSinv[1,1]
                                     + xy * (halfSinv[1,2]+halfSinv[2,1])
                                     + ysq * halfSinv[2,2]))
            Kern <- Kern/sum(Kern)
          } else 
            stop("Must specify either sigma or varcov")
        } else {
          ## non-Gaussian kernel
          ## evaluate kernel at array of points
          xker <- as.vector(xcol.ker[col(Ypad)])
          yker <- as.vector(yrow.ker[row(Ypad)])
          Kern <- evaluate2Dkernel(kernel, xker, yker,
                                   sigma=sigma, varcov=varcov, ...) * kerpixarea
          Kern <- matrix(Kern, ncol=2*nc, nrow=2*nr)
          Kern <- Kern/sum(Kern)
        }

     The multiplication with `kerpixarea` is only done if the kernel is not `"gaussian"`. But after some testing I discovered that due to the `Kern <- Kern / sum(Kern)` line it does not matter if this multiplication is done.

      But then I wonder why it is still there? The 

      `#' WAS:  Kern <- outer(densY.ker, densX.ker, "*") * kerpixarea` 

       comment means that for `kernel = "gaussian"` there was a change made to avoid this unneccessary calculation, right? Why is it still there for the other kernels, then?

Thank you very much for helping!

**Comment by baddstats** [comment]
You have found a bug in the code for `density.ppp` in the case where `at="points",` `leaveoneout=FALSE,` and `kernel` is not the default. The value of the kernel at distance zero is not evaluated correctly in this case.

The bug will be fixed in the development version of `spatstat` shortly.

Regarding your other questions I'm afraid I don't have time to explain what we are doing with this code. It is still under development (as you can see by the comments "Experimental code") to make it run faster. The legacy code is there so we can check that it is still valid.

**Comment by baddstats** [comment]
Bug is now fixed in `spatstat` development version
