### ISSUE TITLE
rthin for spatstat.options(fastthin = TRUE)

### ISSUE THREAD

**Issue by mhesselbarth** [spatstat/spatstat#78]
Dear developers, 

there seems to be something going wrong in the C-code of rthin(). In case P is rather high, in many cases, no point is retained in the resulting pattern at all. However, using the old R-code everything behaves as expected. 

```
set.seed(42)

pattern <- spatstat::runifpoint(n = 25)

spatstat::spatstat.options(fastthin = TRUE)
pattern_thin_a <- spatstat::rthin(pattern, P = 0.975, nsim = 1999)

spatstat::spatstat.options(fastthin = FALSE)
pattern_thin_b <- spatstat::rthin(pattern, P = 0.975, nsim = 1999)

table(sapply(pattern_thin_a, function(x) x$n)) 
 0   19   20   21   22   23   24 
1052    2    1    1   40  209  694 

table(sapply(pattern_thin_b, function(x) x$n))
  21   22   23   24   25 
   4   48  222  708 1017 
```

**Comment by rubak** [comment]
Thanks for reporting this. I will fix it in a bugfix branch immidiately, which can be installed by loading `remotes` or `devtools` and then run `install_github("spatstat/spatstat", ref = "rthin_bugfix")`.

**Comment by mhesselbarth** [comment]
Create, thanks a lot!
