### ISSUE TITLE
nnorient bug

### ISSUE THREAD

**Issue by tomaslaz** [spatstat/spatstat#82]
"nnorient" fails when all the points in the ppp object are corrected with "bord.modif". 

MRE:

test_ppp <- ppp(c(1, 99), c(99, 1), owin(xrange=c(0,100), yrange=c(0,100)))
nnorient(test_ppp)

Throws the following error:

`Error in (function (x, bw = "nrd0", adjust = 1, kernel = c("gaussian",  : 
  'weights' must all be finite`

**Comment by tomaslaz** [comment]
The problem occurs in the following line:

https://github.com/spatstat/spatstat/blob/68d635eb753009a33446c3d34854921dc4bb76f7/R/nnorient.R#L121

Suggestion:
Introduce a stop or return if the sum(edgewt) = 0.

**Comment by rubak** [comment]
@tomaslaz Thanks for spotting this.

@baddstats and @rolfTurner I guess we need to decide what we want to return in this case. Maybe just a function estimate that is identically zero for all argument values?
I don't have time to fix this right now, but when I quickly browsed the code I found another bug with a dangling `else` in line 53 here:
https://github.com/spatstat/spatstat/blob/68d635eb753009a33446c3d34854921dc4bb76f7/R/nnorient.R#L53
This causes an error when the argument `domain` is supplied. Maybe we should also add a test for that case...
So we need to remember to remove the dangling `else` when we fix the other bug.
