### ISSUE TITLE
function Pool does not work properly with eval.fv

### ISSUE THREAD

**Issue by Jack21ss** [spatstat/spatstat#83]
Function "pool" in spatstat seems not to work correctly if applied to a .rat object obtained through eval.fv. Example below:

*K1 <- Kcross(X, "on", "on", correction="isotropic", ratio=TRUE)

K2 <- Kcross(X, "on", "off", correction="isotropic", ratio=TRUE)

Kdiff <- eval.fv(K1 - K2)

pool(Kdiff)*

The result is wrong. It seems the pool function does not correctly pool Kdiff, but instead pools K1. Is there a way around it?

**Comment by rubak** [comment]
What do you expect pool(Kdiff) to calculate?

**Comment by Jack21ss** [comment]
Apologies, I was not clear enough. I have a hyperframe (h) with n observation windows. 

h$K1  <- with(h, Kcross(X, "on", "on",correction="isotropic", ratio=TRUE))
h$K2  <- with(h, Kcross(X, "off", "off", correction="isotropic", ratio=TRUE))
h$Kd <- with(h, eval.fv(K1 - K2))
Kp      <- pool(h$Kd)

Given how "pool" is defined, I expect it to calculate the "aggregate" Kd(r), that is, its weighted average over all 75 observation windows with the 95% confidence interval. Just that instead of pooling a standard K, it would pool a difference between two Ks. But it seems that the function "pool" does not pool Kd (the result of eval.fv) but K1 as I get that same result as when I use
Kp2 <- pool(h$K1).

**Comment by Jack21ss** [comment]
Thanks a lot for this fast solution. This solved my problem. I thought that I needed to use ratio=TRUE whenever I use pool with Kest or Kcross, but it seems pool.fv does not require this.

**Comment by baddstats** [comment]
This does not solve your problem!! 

It appears that you want to perform a statistical test that K1-K2 = 0. The `pool` function is not designed to do this. The `pool` function is designed to combine several estimates of the same thing (e.g.`K1`) to give the best estimate. If ratio information is present (that is, if each estimate of `K1` was obtained as a ratio) then the pooling will be performed by taking the ratio of the sum of numerators divided by the sum of denominators. This is the correct thing to do when the denominator represents sample size of each estimate. It would be the correct thing to do for `K` functions as in your example. The best estimate of the difference `K1-K2` would be 

     K1p <- pool(h$K1)
     K2p <- pool(h$K2)
     Kdifp <- eval.fv(K1p - K2p)

For example `Kdifp$pooliso` is the estimate of the difference using the isotropic correction.

Next you want "confidence intervals" for this estimate. The pooled objects`K1p`, `K2p` contain estimates of variance. For example `K1p$variso` contains a variance (squared standard error) of the pooled estimate `K1p$pooliso`. For the difference `Kdifp$pooliso` the variance estimate is `K1p$variso + K2p$variso` so the standard error of the difference is `sqrt(K1p$variso + K2p$variso)`. So you can then construct significance bands using this standard error.

If this seems like a lot of work, you could look at the command `studpermu.test` which does a very similar job..

**Comment by Jack21ss** [comment]
Thank you for the clarification @baddstats. I'm most likely in wrong, but I think your answer might be overlooking the fact that I have two Kcross functions and not two Kest functions? If my K1 and K2 were Kest functions, I would totally agree with your solution. But given that I have K1 = Kcross(X, "on", "on") and K2 = Kcross(X, "**on**", "off"), I thought that was very much like a paired sample t-test where one needs to calculate the variance of the difference between two variables. Following what you suggest, would we not forget the covariance? In the sense that var(K1 - K2) = var(K1) + var(K2) - 2 cov(K1, K2). That's why I thought I would need to calculate the difference between K1 and K2 (eval.fv(K1-K2)) **before** applying some kind of a "pool" function. But I guess this is not what my initial code did anyway?

**Comment by baddstats** [comment]
`eval.fv` ignores ratio information because it is generally not possible to incorporate ratio information when evaluating an expression.
 
If `K1` is a ratio estimate and `K2` is a ratio estimate, then `K1-K2` is not a ratio estimate unless the denominators are the same. In the case of `Kcross` the denominator is the number of pairs of points that are considered, i.e. the number of pairs of points of type `i` multiplied by the number of points of type `j`. So the denominators are not equal and it would not be possible to make a ratio estimate of `K1-K2` by any simple procedure. 

You can, however, just apply `pool` to the differences `K1-K2` as in your original post. This will dispatch to `pool.fv` which will compute sample means and sample variances, treating each row of the hyperframe as having equal weight (equal denominator). (You could try using the `weights` argument to `pool.fv` to introduce more appropriate weighting.)

**Comment by baddstats** [comment]
I'm going to close this Issue because it's not about a bug in the code. 

If you'd like to continue the conversation, please email us directly.
