### ISSUE TITLE
rmax in Kcross doesn't always work

### ISSUE THREAD

**Issue by Jack21ss** [spatstat/spatstat#85]
Kcross(amacrine, i="on", j="on",  correction="isotropic", rmax=0.1) works,

but

Kcross(amacrine, i="on", j="off",  correction="isotropic", rmax=0.1) does not work. rmax has no effect.

**Comment by rubak** [comment]
Thanks for pointing this out. I can reproduce the problem and will look at a fix later. For now you can just specify `r` directly:

```r
r <- seq(0, 0.1, length.out = 513)
Kcross(amacrine, i="on", j="off", correction="isotropic", r=r)
```

**Comment by rubak** [comment]
I will just leave this open as a reminder to fix it.

**Comment by baddstats** [comment]
`Kcross` does not have an argument `rmax`. (See the help file).

Currently `Kest` is the only summary function which has an argument `rmax`. This is for development purposes. 

In `Kcross`, if the arguments `i` and `j` are equal, then the calculation is performed by calling `Kest` -- and currently that causes the argument `rmax` to be recognised. This explains the inconsistency. 

I do not intend to implement the `rmax` argument in other summary functions in `spatstat` (of which there are almost 100), until we have decided what the right format will be.

Instead, to ensure consistency, I will make `Kcross` ignore the `rmax` argument - which will be consistent with the help file.
