### ISSUE TITLE
Envelope fails with pcf function and nrank argument

### ISSUE THREAD

**Issue by pmarchand1** [spatstat/spatstat#86]
Here is a minimal example:
`plot(envelope(longleaf, pcf, nsim = 20))`
`plot(envelope(longleaf, Kest, nsim = 20, nrank = 2))`
`plot(envelope(longleaf, pcf, nsim = 20, nrank = 2))`

With spatstat 1.56-1 and spatstat.utils 1.12-0, the first two commands work but the third command returns the error 
`Error in sort.int(x, na.last = na.last, decreasing = decreasing, ...) : index 2 outside bounds`

The error did not occur with the same version of spatstat but spatstat.utils 1.9-0. It seems to be triggered by the new version of orderstats via the partial sort, but the orderstats function itself is working.

**Comment by baddstats** [comment]
This is a bug in `spatstat.utils::orderstats` occurring when some of the values to be sorted are NA. 
It will be fixed as soon as possible.

**Comment by baddstats** [comment]
This has been fixed in `spatstat.utils` version `1.13-0`
