### ISSUE TITLE
locally fitted model for cluster process models

### ISSUE THREAD

**Issue by hrheydarian** [spatstat/spatstat#89]
Hi,

In the book, it is mentioned that the function `lockppm()` is going to be included in `spatstat`. However, still we don't have it in the latest version of the package. Is there any plan for update?

**Comment by baddstats** [comment]
The local modelling functions are in the extension package `spatstat.local` available on CRAN. That’s because CRAN policies do not allow us to make `spatstat` larger. 

Just install `spatstat.local` In the usual way.

Instead of `lockppm` there are two functions `locmincon` and `loccit` which fit the same local cluster models by two different methods.

**Comment by hrheydarian** [comment]
> The local modelling functions are in the extension package `spatstat.local` available on CRAN. That’s because CRAN policies do not allow us to make `spatstat` larger.
> 
> Just install `spatstat.local` In the usual way.
> 
> Instead of `lockppm` there are two functions `locmincon` and `loccit` which fit the same local cluster models by two different methods.

Dear Adrian,

Great, thanks for the tip.
I have another question about fitting inhomogeneous Neyman-Scott process in which parents are inhomogenous. In the book (p.465), it is written that this is not currently implemented in `spatstat`. Could you please tell me if this is also implemented in an extended package or not?

Thanks a lot

**Comment by baddstats** [comment]
No, the models mentioned on p 465 of the book are not implemented directly: these models assume that the parent intensity is inhomogeneous but the cluster distribution is homogeneous. 
However, these models are subsumed in the models fitted by `loccit` and `locmincon` which allow **both** the parent intensity **and** the cluster distribution to be inhomogeneous.

**Comment by hrheydarian** [comment]
> No, the models mentioned on p 465 of the book are not implemented directly: these models assume that the parent intensity is inhomogeneous but the cluster distribution is homogeneous.
> However, these models are subsumed in the models fitted by `loccit` and `locmincon` which allow **both** the parent intensity **and** the cluster distribution to be inhomogeneous.

Thanks a lot for the explanation.
