### ISSUE TITLE
bug in rotmean

### ISSUE THREAD

**Issue by hrheydarian** [spatstat/spatstat#91]
Hi,

In the documentation for [rotmean](https://rdrr.io/cran/spatstat/man/rotmean.html) function, it is mentioned that with `result="im"` the output have the same dimensions as the input image. However, it seems that this does not work. I tried this with the following example usage of the documentation and the image ZZ is larger than the input:

`Z <- setcov(square(1))`   
`ZZ<-rotmean(Z, result="im")`

**Comment by baddstats** [comment]
Thank you for spotting this bug. It will be fixed immediately.

**Comment by baddstats** [comment]
Is now fixed.
