### ISSUE TITLE
Add functions to calculate slopes and intercepts of psp objects?

### ISSUE THREAD

**Issue by MikkoVihtakari** [spatstat/spatstat#98]
Hi,

I just happened to need functions to calculate slopes and intercepts of psp objects. These functions are pretty straightforward but will post them here in case you want to add them to the spatstat package or to one of its satellites. My apologies if the functions already exist.

```
  #' @title Calculate slopes for a spatstat psp object
  #' @description Calculates a slope for each line segment in a psp object
  #' @param x a \code{\link[spatsta]{psp}} object
  #' @param orthogonal logical indicating whether a slope for orthogonal line to \code{x} should be returned instead of slope for \code{x}
  #' @return Returns a numeric vector containing slopes of line segments in the same order than \code{x}
  #' @details The function assumes that each line segment has an infinite domain and follows the line equation $y = slope * x + intercept$.
  #' @author Mikko Vihtakari

  slope.psp <- function(x, orthogonal = FALSE) {
  out <- (x$ends$y0 - x$ends$y1)/(x$ends$x0 - x$ends$x1)

  if(orthogonal) {
    -1/out
  } else {
    out
  }
}

  #' @title Calculate intercept for a spatstat psp object
  #' @description Calculates an intercept for each line segment in a psp object
  #' @param x a \code{\link[spatsta]{psp}} object
  #' @return Returns a numeric vector containing y-intercepts of line segments in the same order than \code{x}
  #' @details The function assumes that each line segment has an infinite domain and follows the line equation $y = slope * x + intercept$.
  #' @author Mikko Vihtakari

  intercept.psp <- function(x) {
    x$ends$y0 - slope(x) * x$ends$x0
  }
 
```

**Comment by baddstats** [comment]
Thanks for the suggestion. 

This could be slightly dangerous (in my experience) as it might lead some users to think that the segments in a `psp` object are infinite lines. 

We could introduce an operator (`as.infline` or `extrapolate.psp`) to convert the segments to the `infline` class, from which one can then extract slope and intercept. I will investigate.

**Comment by baddstats** [comment]
I have created `extrapolate.psp` in the development version of `spatstat`

**Comment by MikkoVihtakari** [comment]
An example where one might need a slope is if you want to rotate all objects relative to a single segment (i.e. a psp with n = 1). Then rotating various objects with `angle = pi - atan(slope)` makes everything (`owin`, `ppp`, `psp`, etc) aligned to this single segment (I defined x-axis using the segment). Calling such objects `infline` might make sense for intercepts, but any psp will has a slope.

**Comment by baddstats** [comment]
The orientation of a segment can already be computed using `angles.psp`. 

Class `infline` already exists in `spatstat` and such objects can be rotated, etc

**Comment by MikkoVihtakari** [comment]
> The orientation of a segment can already be computed using `angles.psp`.
> 
> Class `infline` already exists in `spatstat` and such objects can be rotated, etc

Ok, sorry for not being up to date. Many functions to remember :)

**Comment by MikkoVihtakari** [comment]
How about adding the option for getting the slope and orthogonal angle/slope within the `angles.psp`? Or would this just be confusing? Maybe `slopes.psp` would be more logical?

**Comment by baddstats** [comment]
No worries. Any suggestions for improvements to the documentation would be welcome!

**Comment by baddstats** [comment]
I think `tan(angles.psp(X))` is easy enough that it does not require a separate function
